"""
Dynamic Database Configuration
Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct), enhanced by Expert

Supports:
- Environment variable configuration
- PostgreSQL and SQLite backends
- Connection pooling
- Runtime configuration
"""
import os
from typing import Optional
from pydantic_settings import BaseSettings
from functools import lru_cache


class DatabaseSettings(BaseSettings):
    """Database configuration with environment variable support."""

    # Primary connection string (takes priority if set)
    DATABASE_URL: Optional[str] = None

    # Individual connection parameters
    DB_HOST: str = "localhost"
    DB_PORT: int = 5432
    DB_NAME: str = "northwind"
    DB_USER: str = "dqm_user"
    DB_PASSWORD: str = "dqm_password"

    # Connection pool settings
    DB_POOL_SIZE: int = 5
    DB_POOL_MAX_OVERFLOW: int = 10
    DB_POOL_TIMEOUT: int = 30

    # Database type (postgresql or sqlite)
    DB_TYPE: str = "postgresql"

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
        extra = "ignore"

    def get_connection_string(self) -> str:
        """Build connection string, prioritizing DATABASE_URL if set."""
        if self.DATABASE_URL:
            return self.DATABASE_URL

        if self.DB_TYPE == "sqlite":
            return f"sqlite:///./{self.DB_NAME}.db"

        return (
            f"postgresql://{self.DB_USER}:{self.DB_PASSWORD}"
            f"@{self.DB_HOST}:{self.DB_PORT}/{self.DB_NAME}"
        )

    def get_async_connection_string(self) -> str:
        """Build async connection string for asyncpg."""
        if self.DATABASE_URL:
            # Convert postgresql:// to postgresql+asyncpg://
            url = self.DATABASE_URL
            if url.startswith("postgresql://"):
                return url.replace("postgresql://", "postgresql+asyncpg://", 1)
            return url

        if self.DB_TYPE == "sqlite":
            return f"sqlite+aiosqlite:///./{self.DB_NAME}.db"

        return (
            f"postgresql+asyncpg://{self.DB_USER}:{self.DB_PASSWORD}"
            f"@{self.DB_HOST}:{self.DB_PORT}/{self.DB_NAME}"
        )


@lru_cache()
def get_database_settings() -> DatabaseSettings:
    """Get cached database settings instance."""
    return DatabaseSettings()


# Convenience exports
database_settings = get_database_settings()
DATABASE_URL = database_settings.get_connection_string()
ASYNC_DATABASE_URL = database_settings.get_async_connection_string()
