/**
 * AIAnalysisPanel Component - AI-powered data analysis
 * Generated by: RTX 3050 (Qwen2.5-Coder-7B)
 */
import React from 'react';
import { useAIAnalysis } from '../hooks';

const AIAnalysisPanel = ({ tableName, profilingData }) => {
  const { insights, anomalies, loading, error, analyzeProfile, detectAnomalies } = useAIAnalysis(tableName);

  const handleAnalyze = async () => {
    if (profilingData) {
      await analyzeProfile(profilingData);
    }
  };

  const handleDetectAnomalies = async () => {
    if (profilingData) {
      await detectAnomalies({ [tableName]: profilingData });
    }
  };

  return (
    <div className="p-4 bg-white rounded-lg shadow">
      <h2 className="text-xl font-bold mb-4">AI Analysis</h2>

      <div className="flex gap-2 mb-4">
        <button
          onClick={handleAnalyze}
          disabled={loading || !profilingData}
          className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:bg-gray-400"
        >
          {loading ? 'Analyzing...' : 'Analyze Profile'}
        </button>
        <button
          onClick={handleDetectAnomalies}
          disabled={loading || !profilingData}
          className="px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600 disabled:bg-gray-400"
        >
          {loading ? 'Detecting...' : 'Detect Anomalies'}
        </button>
      </div>

      {error && <div className="text-red-500 mb-4">Error: {error}</div>}

      {insights && (
        <div className="mb-4">
          <h3 className="text-lg font-semibold mb-2">Insights</h3>
          <ul className="list-disc pl-6 space-y-1">
            {insights.insights?.map((insight, idx) => (
              <li key={idx} className="text-gray-700">
                <span className="font-medium">{insight.type}:</span> {insight.description}
              </li>
            ))}
          </ul>
        </div>
      )}

      {anomalies && anomalies.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold mb-2">Anomalies Detected</h3>
          <ul className="list-disc pl-6 space-y-1">
            {anomalies.map((anomaly, idx) => (
              <li key={idx} className="text-red-600">
                <span className="font-medium">{anomaly.type}:</span> {anomaly.description}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};

export default AIAnalysisPanel;
