/**
 * AnalysisResultsPanel Component
 * Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
 */
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import PropTypes from 'prop-types';

const AnalysisResultsPanel = ({ theme }) => {
  const [analysisHistory, setAnalysisHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [newIssue, setNewIssue] = useState('');

  useEffect(() => {
    fetchAnalysisHistory();
  }, []);

  const fetchAnalysisHistory = async () => {
    try {
      setLoading(true);
      const response = await axios.get('/api/analysis/history');
      setAnalysisHistory(response.data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleNewAnalysis = async () => {
    if (!newIssue.trim()) {
      setError('Please describe the issue to analyze');
      return;
    }

    try {
      setAnalyzing(true);
      setError(null);
      const response = await axios.post('/api/analysis/ai', { issue: newIssue });
      setAnalysisHistory([response.data, ...analysisHistory]);
      setNewIssue('');
    } catch (err) {
      setError(err.message);
    } finally {
      setAnalyzing(false);
    }
  };

  const themeStyles = {
    backgroundColor: theme === 'dark' ? '#1e1e1e' : '#ffffff',
    color: theme === 'dark' ? '#ffffff' : '#333333',
    padding: '20px',
    borderRadius: '8px',
  };

  return (
    <div style={themeStyles}>
      <h2>AI Analysis Results</h2>

      {/* New Analysis Form */}
      <div style={{ marginBottom: '20px' }}>
        <h3>Trigger New Analysis</h3>
        <input
          type="text"
          value={newIssue}
          onChange={(e) => setNewIssue(e.target.value)}
          placeholder="Describe the data quality issue..."
          style={{
            width: '70%',
            padding: '10px',
            marginRight: '10px',
            borderRadius: '4px',
            border: '1px solid #ccc',
          }}
        />
        <button
          onClick={handleNewAnalysis}
          disabled={analyzing}
          style={{
            padding: '10px 20px',
            backgroundColor: analyzing ? '#ccc' : '#007bff',
            color: '#fff',
            border: 'none',
            borderRadius: '4px',
            cursor: analyzing ? 'not-allowed' : 'pointer',
          }}
        >
          {analyzing ? 'Analyzing...' : 'Analyze'}
        </button>
      </div>

      {error && <p style={{ color: 'red' }}>Error: {error}</p>}

      {/* Analysis History */}
      {loading ? (
        <p>Loading history...</p>
      ) : (
        <div>
          <h3>Analysis History</h3>
          {analysisHistory.length === 0 ? (
            <p>No analysis results yet.</p>
          ) : (
            <ul style={{ listStyle: 'none', padding: 0 }}>
              {analysisHistory.map((analysis, index) => (
                <li key={index} style={{ marginBottom: '15px' }}>
                  <details style={{
                    backgroundColor: theme === 'dark' ? '#2d2d2d' : '#f5f5f5',
                    padding: '10px',
                    borderRadius: '4px',
                  }}>
                    <summary style={{ cursor: 'pointer', fontWeight: 'bold' }}>
                      {analysis.timestamp || new Date().toISOString()} - {analysis.issue || 'Analysis'}
                    </summary>
                    <pre style={{
                      marginTop: '10px',
                      padding: '10px',
                      backgroundColor: theme === 'dark' ? '#1a1a1a' : '#eee',
                      borderRadius: '4px',
                      overflow: 'auto',
                    }}>
                      {JSON.stringify(analysis.findings || analysis, null, 2)}
                    </pre>
                  </details>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
};

AnalysisResultsPanel.propTypes = {
  theme: PropTypes.oneOf(['light', 'dark']).isRequired,
};

export default AnalysisResultsPanel;
