/**
 * DAMAFilter Component - V88
 * Filter dropdown for DAMA Data Quality Dimensions
 * Generated by RTX 3050 (Qwen2.5-Coder-7B), enhanced by Claude
 */
import React, { useState } from 'react';

const DAMA_DIMENSIONS = [
  { value: 'completeness', label: 'Completeness', description: 'All required data values are present' },
  { value: 'uniqueness', label: 'Uniqueness', description: 'Duplicate records are minimized' },
  { value: 'validity', label: 'Validity', description: 'Data conforms to defined rules' },
  { value: 'accuracy', label: 'Accuracy', description: 'Data accurately reflects real-world entities' },
  { value: 'integrity', label: 'Integrity', description: 'Relationships between data are correct' },
  { value: 'consistency', label: 'Consistency', description: 'Data is consistent across systems' },
  { value: 'timeliness', label: 'Timeliness', description: 'Data is available when needed' },
  { value: 'precision', label: 'Precision', description: 'Data is at the right level of detail' },
  { value: 'relevance', label: 'Relevance', description: 'Data is appropriate for its use' }
];

function DAMAFilter({ selectedDimensions = [], onFilterChange, compact = false }) {
  const [isOpen, setIsOpen] = useState(false);

  const handleToggle = (dimension) => {
    const newSelection = selectedDimensions.includes(dimension)
      ? selectedDimensions.filter(d => d !== dimension)
      : [...selectedDimensions, dimension];
    onFilterChange(newSelection);
  };

  const handleSelectAll = () => {
    if (selectedDimensions.length === DAMA_DIMENSIONS.length) {
      onFilterChange([]);
    } else {
      onFilterChange(DAMA_DIMENSIONS.map(d => d.value));
    }
  };

  const handleClear = () => {
    onFilterChange([]);
  };

  const getFilterLabel = () => {
    if (selectedDimensions.length === 0) return 'All Dimensions';
    if (selectedDimensions.length === DAMA_DIMENSIONS.length) return 'All Dimensions';
    if (selectedDimensions.length === 1) {
      const dim = DAMA_DIMENSIONS.find(d => d.value === selectedDimensions[0]);
      return dim ? dim.label : 'All Dimensions';
    }
    return `${selectedDimensions.length} Dimensions`;
  };

  return (
    <div className="dama-filter" style={{ position: 'relative', display: 'inline-block' }}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="btn secondary"
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          padding: compact ? '4px 8px' : '8px 12px',
          fontSize: compact ? '12px' : '14px'
        }}
      >
        <span>DAMA: {getFilterLabel()}</span>
        <span style={{ fontSize: '10px' }}>{isOpen ? '▲' : '▼'}</span>
      </button>

      {isOpen && (
        <div
          className="dama-filter-dropdown"
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            zIndex: 1000,
            background: 'white',
            border: '1px solid #ddd',
            borderRadius: '8px',
            boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
            minWidth: '280px',
            marginTop: '4px'
          }}
        >
          <div style={{ padding: '8px 12px', borderBottom: '1px solid #eee', display: 'flex', gap: '8px' }}>
            <button onClick={handleSelectAll} className="btn small" style={{ fontSize: '11px', padding: '4px 8px' }}>
              {selectedDimensions.length === DAMA_DIMENSIONS.length ? 'Deselect All' : 'Select All'}
            </button>
            <button onClick={handleClear} className="btn small" style={{ fontSize: '11px', padding: '4px 8px' }}>
              Clear
            </button>
          </div>

          <div style={{ maxHeight: '300px', overflowY: 'auto' }}>
            {DAMA_DIMENSIONS.map(dim => (
              <label
                key={dim.value}
                style={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: '8px',
                  padding: '8px 12px',
                  cursor: 'pointer',
                  borderBottom: '1px solid #f0f0f0',
                  background: selectedDimensions.includes(dim.value) ? '#f0f7ff' : 'transparent'
                }}
                title={dim.description}
              >
                <input
                  type="checkbox"
                  checked={selectedDimensions.includes(dim.value)}
                  onChange={() => handleToggle(dim.value)}
                  style={{ marginTop: '2px' }}
                />
                <div>
                  <div style={{ fontWeight: 500, fontSize: '13px' }}>{dim.label}</div>
                  <div style={{ fontSize: '11px', color: '#666', marginTop: '2px' }}>{dim.description}</div>
                </div>
              </label>
            ))}
          </div>
        </div>
      )}

      {/* Click outside to close */}
      {isOpen && (
        <div
          style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, zIndex: 999 }}
          onClick={() => setIsOpen(false)}
        />
      )}
    </div>
  );
}

export default DAMAFilter;
export { DAMA_DIMENSIONS };
