/**
 * DAMALegend Component - V89
 * Prominent legend showing all 9 DAMA Data Quality Dimensions
 * Generated by Claude Code with RTX 5090/3050 architecture
 */
import React from 'react';

const DAMA_DIMENSIONS = [
  { id: 'completeness', color: '#4CAF50', label: 'Completeness', desc: 'All required data values are present' },
  { id: 'uniqueness', color: '#2196F3', label: 'Uniqueness', desc: 'Duplicate records are minimized' },
  { id: 'validity', color: '#9C27B0', label: 'Validity', desc: 'Data conforms to defined rules' },
  { id: 'accuracy', color: '#FF5722', label: 'Accuracy', desc: 'Data accurately reflects real-world entities' },
  { id: 'integrity', color: '#607D8B', label: 'Integrity', desc: 'Relationships between data are correct' },
  { id: 'consistency', color: '#795548', label: 'Consistency', desc: 'Data is consistent across systems' },
  { id: 'timeliness', color: '#FF9800', label: 'Timeliness', desc: 'Data is available when needed' },
  { id: 'precision', color: '#00BCD4', label: 'Precision', desc: 'Data is at the right level of detail' },
  { id: 'relevance', color: '#E91E63', label: 'Relevance', desc: 'Data is appropriate for its use' }
];

function DAMALegend({ compact = false }) {
  if (compact) {
    return (
      <div className="dama-legend-compact" style={{
        display: 'flex',
        flexWrap: 'wrap',
        gap: '8px',
        padding: '8px',
        background: '#f5f5f5',
        borderRadius: '4px',
        marginBottom: '16px'
      }}>
        <span style={{ fontWeight: 600, marginRight: '8px' }}>DAMA Dimensions:</span>
        {DAMA_DIMENSIONS.map(dim => (
          <span
            key={dim.id}
            title={dim.desc}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '4px',
              fontSize: '12px',
              cursor: 'help'
            }}
          >
            <span style={{
              width: '10px',
              height: '10px',
              borderRadius: '50%',
              background: dim.color
            }} />
            {dim.label}
          </span>
        ))}
      </div>
    );
  }

  return (
    <div className="dama-legend" style={{
      padding: '16px',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      borderRadius: '8px',
      marginBottom: '20px',
      color: 'white'
    }}>
      <h3 style={{ margin: '0 0 12px 0', fontSize: '16px' }}>
        DAMA Data Quality Dimensions (9)
      </h3>
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
        gap: '8px'
      }}>
        {DAMA_DIMENSIONS.map(dim => (
          <div
            key={dim.id}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
              padding: '6px 10px',
              background: 'rgba(255,255,255,0.15)',
              borderRadius: '4px',
              borderLeft: `4px solid ${dim.color}`
            }}
          >
            <span style={{ fontWeight: 600, minWidth: '100px' }}>{dim.label}</span>
            <span style={{ fontSize: '12px', opacity: 0.9 }}>{dim.desc}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

export default DAMALegend;
export { DAMA_DIMENSIONS };
