/**
 * DataQualityRulesPanel Component - Manage DQ rules
 * Generated by: RTX 3050 (Qwen2.5-Coder-7B)
 */
import React, { useState } from 'react';
import { useDataQuality } from '../hooks';

const DataQualityRulesPanel = () => {
  const { rules, loading, error, addRule, updateRule, deleteRule, toggleRule } = useDataQuality();
  const [showForm, setShowForm] = useState(false);
  const [formData, setFormData] = useState({
    rule_name: '',
    rule_type: 'not_null',
    table_name: '',
    column_name: '',
    sql_expression: ''
  });

  const handleInputChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await addRule(formData);
      setFormData({ rule_name: '', rule_type: 'not_null', table_name: '', column_name: '', sql_expression: '' });
      setShowForm(false);
    } catch (err) {
      console.error('Failed to add rule:', err);
    }
  };

  return (
    <div className="p-4 bg-white rounded-lg shadow">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-bold">Data Quality Rules</h2>
        <button
          onClick={() => setShowForm(!showForm)}
          className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
        >
          {showForm ? 'Cancel' : 'Add Rule'}
        </button>
      </div>

      {showForm && (
        <form onSubmit={handleSubmit} className="mb-4 p-4 bg-gray-50 rounded space-y-3">
          <div className="grid grid-cols-2 gap-4">
            <input name="rule_name" value={formData.rule_name} onChange={handleInputChange}
              placeholder="Rule Name" className="p-2 border rounded" required />
            <select name="rule_type" value={formData.rule_type} onChange={handleInputChange}
              className="p-2 border rounded">
              <option value="not_null">Not Null</option>
              <option value="unique">Unique</option>
              <option value="range">Range</option>
              <option value="custom">Custom SQL</option>
            </select>
            <input name="table_name" value={formData.table_name} onChange={handleInputChange}
              placeholder="Table Name" className="p-2 border rounded" required />
            <input name="column_name" value={formData.column_name} onChange={handleInputChange}
              placeholder="Column Name" className="p-2 border rounded" />
          </div>
          {formData.rule_type === 'custom' && (
            <textarea name="sql_expression" value={formData.sql_expression} onChange={handleInputChange}
              placeholder="SQL Expression (SELECT only)" className="w-full p-2 border rounded" rows={3} />
          )}
          <button type="submit" className="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600">
            Save Rule
          </button>
        </form>
      )}

      {loading && <div className="text-blue-500">Loading rules...</div>}
      {error && <div className="text-red-500">Error: {error}</div>}

      <div className="space-y-2">
        {rules.map((rule) => (
          <div key={rule.id} className="flex justify-between items-center p-3 bg-gray-50 rounded">
            <div>
              <span className="font-medium">{rule.rule_name}</span>
              <span className="ml-2 px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded">{rule.rule_type}</span>
              <span className="ml-2 text-gray-500 text-sm">{rule.table_name}.{rule.column_name}</span>
            </div>
            <div className="flex gap-2">
              <button onClick={() => toggleRule(rule.id)}
                className={`px-3 py-1 rounded text-sm ${rule.is_active ? 'bg-green-100 text-green-800' : 'bg-gray-200 text-gray-600'}`}>
                {rule.is_active ? 'Active' : 'Inactive'}
              </button>
              <button onClick={() => deleteRule(rule.id)}
                className="px-3 py-1 bg-red-100 text-red-800 rounded text-sm hover:bg-red-200">
                Delete
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default DataQualityRulesPanel;
