/**
 * DataProfilingDashboard Component - Display table profiling results
 * Generated by: RTX 3050 (Qwen2.5-Coder-7B)
 */
import React, { useState, useEffect } from 'react';
import { useDataProfiling } from '../hooks';

const DataProfilingDashboard = () => {
  const [selectedTable, setSelectedTable] = useState('');
  const { profilingData, tables, loading, error, refetch } = useDataProfiling(selectedTable);

  const handleTableChange = (e) => {
    setSelectedTable(e.target.value);
  };

  return (
    <div className="p-4 bg-white rounded-lg shadow">
      <h2 className="text-xl font-bold mb-4">Data Profiling Dashboard</h2>

      <div className="mb-4">
        <label className="block text-sm font-medium text-gray-700 mb-2">Select Table</label>
        <select
          value={selectedTable}
          onChange={handleTableChange}
          className="w-full p-2 border rounded focus:ring-2 focus:ring-blue-500"
        >
          <option value="">-- Select a table --</option>
          {tables.map((table) => (
            <option key={table} value={table}>{table}</option>
          ))}
        </select>
      </div>

      {loading && <div className="text-blue-500">Loading profiling data...</div>}
      {error && <div className="text-red-500">Error: {error}</div>}

      {profilingData && profilingData.columns && (
        <>
          <div className="mb-4 p-3 bg-gray-100 rounded">
            <span className="font-semibold">Row Count:</span> {profilingData.row_count?.toLocaleString() || 'N/A'}
          </div>
          <table className="w-full border-collapse">
            <thead>
              <tr className="bg-gray-200">
                <th className="border px-4 py-2 text-left">Column Name</th>
                <th className="border px-4 py-2 text-left">Data Type</th>
                <th className="border px-4 py-2 text-right">Null %</th>
                <th className="border px-4 py-2 text-right">Distinct %</th>
              </tr>
            </thead>
            <tbody>
              {profilingData.columns.map((col) => (
                <tr key={col.column_name} className="hover:bg-gray-50">
                  <td className="border px-4 py-2">{col.column_name}</td>
                  <td className="border px-4 py-2">{col.data_type}</td>
                  <td className="border px-4 py-2 text-right">{col.null_percentage?.toFixed(2) || 0}%</td>
                  <td className="border px-4 py-2 text-right">{col.distinct_percentage?.toFixed(2) || 0}%</td>
                </tr>
              ))}
            </tbody>
          </table>
          <button
            onClick={refetch}
            className="mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
          >
            Refresh
          </button>
        </>
      )}
    </div>
  );
};

export default DataProfilingDashboard;
