/**
 * DatabaseConnectionManager Component
 * V79 Enhancement: Switch between local PostgreSQL and Azure SQL
 * Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
 * Architecture by RTX 5090 (Qwen2.5-Coder-32B-Instruct-AWQ)
 */
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import './DatabaseConnectionManager.css';

const API_BASE = 'http://localhost:8001';

const DatabaseConnectionManager = ({ onConnectionChange }) => {
  const [connections, setConnections] = useState([]);
  const [activeConnection, setActiveConnection] = useState(null);
  const [showForm, setShowForm] = useState(false);
  const [testing, setTesting] = useState(false);
  const [switching, setSwitching] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(null);

  const [newConnection, setNewConnection] = useState({
    name: '',
    db_type: 'postgresql',
    host: '',
    port: 5432,
    database: '',
    username: '',
    password: ''
  });

  useEffect(() => {
    fetchConnections();
    fetchActiveConnection();
  }, []);

  const fetchConnections = async () => {
    try {
      const response = await axios.get(`${API_BASE}/connections`);
      setConnections(response.data);
    } catch (err) {
      console.error('Error fetching connections:', err);
    }
  };

  const fetchActiveConnection = async () => {
    try {
      const response = await axios.get(`${API_BASE}/connections/active`);
      setActiveConnection(response.data);
    } catch (err) {
      console.error('Error fetching active connection:', err);
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setNewConnection(prev => ({
      ...prev,
      [name]: name === 'port' ? parseInt(value) || 5432 : value
    }));
  };

  const testConnection = async () => {
    setTesting(true);
    setError(null);
    setSuccess(null);

    try {
      const response = await axios.post(`${API_BASE}/connections/test`, {
        host: newConnection.host,
        port: newConnection.port,
        database: newConnection.database,
        username: newConnection.username,
        password: newConnection.password,
        db_type: newConnection.db_type
      });

      if (response.data.status === 'success') {
        setSuccess('Connection test successful!');
      }
    } catch (err) {
      setError(err.response?.data?.detail || 'Connection test failed');
    } finally {
      setTesting(false);
    }
  };

  const saveConnection = async () => {
    setError(null);
    setSuccess(null);

    if (!newConnection.name) {
      setError('Connection name is required');
      return;
    }

    try {
      await axios.post(`${API_BASE}/connections`, newConnection);
      setSuccess(`Connection '${newConnection.name}' saved`);
      fetchConnections();
      setNewConnection({
        name: '',
        db_type: 'postgresql',
        host: '',
        port: 5432,
        database: '',
        username: '',
        password: ''
      });
      setShowForm(false);
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to save connection');
    }
  };

  const switchConnection = async (name) => {
    setSwitching(true);
    setError(null);
    setSuccess(null);

    try {
      await axios.post(`${API_BASE}/connections/switch?name=${name}`);
      setSuccess(`Switched to '${name}'`);
      fetchConnections();
      fetchActiveConnection();
      if (onConnectionChange) {
        onConnectionChange(name);
      }
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to switch connection');
    } finally {
      setSwitching(false);
    }
  };

  const deleteConnection = async (name) => {
    if (!window.confirm(`Delete connection '${name}'?`)) return;

    try {
      await axios.delete(`${API_BASE}/connections/${name}`);
      setSuccess(`Connection '${name}' deleted`);
      fetchConnections();
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to delete connection');
    }
  };

  return (
    <div className="db-connection-manager">
      <div className="manager-header">
        <h3>Database Connections</h3>
        <button
          className="add-btn"
          onClick={() => setShowForm(!showForm)}
        >
          {showForm ? 'Cancel' : '+ Add Connection'}
        </button>
      </div>

      {error && <div className="error-message">{error}</div>}
      {success && <div className="success-message">{success}</div>}

      {/* Active Connection Display */}
      {activeConnection && (
        <div className="active-connection">
          <span className="label">Active:</span>
          <span className="value">
            {activeConnection.name} ({activeConnection.host}/{activeConnection.database})
          </span>
          {activeConnection.is_default && <span className="badge default">Default</span>}
        </div>
      )}

      {/* Connection Form */}
      {showForm && (
        <div className="connection-form">
          <h4>New Connection</h4>
          <div className="form-grid">
            <div className="form-group">
              <label>Name</label>
              <input
                type="text"
                name="name"
                value={newConnection.name}
                onChange={handleInputChange}
                placeholder="e.g., Azure Production"
              />
            </div>
            <div className="form-group">
              <label>Type</label>
              <select
                name="db_type"
                value={newConnection.db_type}
                onChange={handleInputChange}
              >
                <option value="postgresql">PostgreSQL</option>
                <option value="azure">Azure SQL</option>
              </select>
            </div>
            <div className="form-group">
              <label>Host</label>
              <input
                type="text"
                name="host"
                value={newConnection.host}
                onChange={handleInputChange}
                placeholder="localhost or server.database.windows.net"
              />
            </div>
            <div className="form-group">
              <label>Port</label>
              <input
                type="number"
                name="port"
                value={newConnection.port}
                onChange={handleInputChange}
              />
            </div>
            <div className="form-group">
              <label>Database</label>
              <input
                type="text"
                name="database"
                value={newConnection.database}
                onChange={handleInputChange}
                placeholder="northwind"
              />
            </div>
            <div className="form-group">
              <label>Username</label>
              <input
                type="text"
                name="username"
                value={newConnection.username}
                onChange={handleInputChange}
                placeholder="postgres"
              />
            </div>
            <div className="form-group full-width">
              <label>Password</label>
              <input
                type="password"
                name="password"
                value={newConnection.password}
                onChange={handleInputChange}
              />
            </div>
          </div>
          <div className="form-actions">
            <button
              onClick={testConnection}
              disabled={testing}
              className="test-btn"
            >
              {testing ? 'Testing...' : 'Test Connection'}
            </button>
            <button
              onClick={saveConnection}
              className="save-btn"
            >
              Save Connection
            </button>
          </div>
        </div>
      )}

      {/* Connections List */}
      <div className="connections-list">
        {connections.map(conn => (
          <div
            key={conn.name}
            className={`connection-item ${conn.is_active ? 'active' : ''}`}
          >
            <div className="connection-info">
              <span className="connection-name">{conn.name}</span>
              {conn.message && <span className="connection-message">{conn.message}</span>}
            </div>
            <div className="connection-actions">
              {!conn.is_active && (
                <button
                  onClick={() => switchConnection(conn.name)}
                  disabled={switching}
                  className="switch-btn"
                >
                  {switching ? '...' : 'Switch'}
                </button>
              )}
              {conn.name !== 'default' && !conn.is_active && (
                <button
                  onClick={() => deleteConnection(conn.name)}
                  className="delete-btn"
                >
                  Delete
                </button>
              )}
              {conn.is_active && <span className="active-badge">Active</span>}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default DatabaseConnectionManager;
