/**
 * DataProfiling Component - V83 Enhancement
 * Multi-table selection support added
 * Generated by RTX 3050 with RTX 5090 architecture guidance
 */
import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import MultiTableSelector from './MultiTableSelector';

const Container = styled.div`
  background-color: #121212;
  color: #ffffff;
  padding: 20px;
`;

const Section = styled.div`
  margin-bottom: 20px;
  padding: 15px;
  background-color: #1e1e1e;
  border-radius: 8px;
`;

const Select = styled.select`
  background-color: #282828;
  color: #ffffff;
  border: 1px solid #444444;
  padding: 8px;
  margin-right: 10px;
`;

const Button = styled.button`
  background-color: #007bff;
  color: #ffffff;
  border: none;
  padding: 10px 20px;
  cursor: pointer;
  margin-right: 10px;
  border-radius: 4px;

  &:disabled {
    background-color: #555;
    cursor: not-allowed;
  }

  &.secondary {
    background-color: #28a745;
  }
`;

const Table = styled.table`
  width: 100%;
  border-collapse: collapse;
  margin-top: 15px;
`;

const Th = styled.th`
  background-color: #333333;
  color: #ffffff;
  padding: 10px;
  text-align: left;
`;

const Td = styled.td`
  border: 1px solid #444444;
  padding: 10px;
`;

const BatchResults = styled.div`
  padding: 15px;
  background: linear-gradient(135deg, #1a3a1a 0%, #1e1e1e 100%);
  border-radius: 8px;
  margin-bottom: 20px;
  border-left: 4px solid #28a745;
`;

const DataProfiling = () => {
  const [tables, setTables] = useState([]);
  const [selectedTable, setSelectedTable] = useState('');
  const [selectedTables, setSelectedTables] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [results, setResults] = useState(null);
  const [batchResults, setBatchResults] = useState(null);
  const [storedResults, setStoredResults] = useState([]);

  useEffect(() => {
    const fetchTables = async () => {
      try {
        const response = await fetch('/data-profiling/tables');
        const data = await response.json();
        setTables(data);
      } catch (err) {
        setError(err);
      }
    };
    fetchTables();
  }, []);

  useEffect(() => {
    if (selectedTable) {
      loadStoredResults();
    }
  }, [selectedTable]);

  const loadStoredResults = async () => {
    try {
      const res = await fetch(`/data-profiling/results?table=${selectedTable}`);
      const data = await res.json();
      setStoredResults(data);
    } catch (err) {
      console.error('Failed to load stored results:', err);
    }
  };

  const handleTableChange = (e) => {
    setSelectedTable(e.target.value);
  };

  const handleRunProfiling = async () => {
    if (!selectedTable) return;
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`/data-profiling/profile/${selectedTable}/run`, {
        method: 'POST',
      });
      const data = await response.json();
      setResults(data);
      loadStoredResults();
    } catch (err) {
      setError(err);
    } finally {
      setLoading(false);
    }
  };

  // V83: Batch profile multiple tables
  const runBatchProfiling = async () => {
    if (selectedTables.length === 0) {
      setError({ message: 'Please select at least one table' });
      return;
    }
    setLoading(true);
    setError(null);
    setBatchResults(null);

    try {
      const results = { successful: 0, failed: 0, profiles: [] };

      for (const table of selectedTables) {
        try {
          const res = await fetch(`/data-profiling/profile/${table}/run`, {
            method: 'POST'
          });
          const data = await res.json();
          results.profiles.push({ table, success: true, data });
          results.successful++;
        } catch (err) {
          results.profiles.push({ table, success: false, error: err.message });
          results.failed++;
        }
      }

      setBatchResults(results);

      // If single table selected, show its details
      if (selectedTables.length === 1) {
        setSelectedTable(selectedTables[0]);
        loadStoredResults();
      }
    } catch (err) {
      setError({ message: 'Batch profiling failed: ' + err.message });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container>
      <h2>Data Profiling</h2>

      {/* V83: Multi-Table Selection */}
      <Section>
        <MultiTableSelector
          tables={tables}
          selectedTables={selectedTables}
          onSelectionChange={setSelectedTables}
          disabled={loading}
        />
        <Button
          onClick={runBatchProfiling}
          disabled={selectedTables.length === 0 || loading}
          className="secondary"
          style={{ marginTop: '10px' }}
        >
          {loading ? 'Profiling...' : `Profile Selected (${selectedTables.length})`}
        </Button>
      </Section>

      {/* Batch Results */}
      {batchResults && (
        <BatchResults>
          <h4>Batch Profiling Complete</h4>
          <p>Successful: {batchResults.successful} | Failed: {batchResults.failed}</p>
        </BatchResults>
      )}

      {/* Single Table Selection for Details */}
      <Section>
        <h4>View Table Details</h4>
        <Select value={selectedTable} onChange={handleTableChange}>
          <option value="">Select a table for details...</option>
          {tables.map((table) => (
            <option key={table} value={table}>
              {table}
            </option>
          ))}
        </Select>
        <Button onClick={handleRunProfiling} disabled={!selectedTable || loading}>
          {loading ? 'Running...' : 'Run Single'}
        </Button>
      </Section>

      {error && <p style={{ color: '#ff6b6b' }}>Error: {error.message}</p>}

      {results && (
        <Section>
          <h3>Profiling Results</h3>
          <p>Columns profiled: {results.columns_profiled || Object.keys(results).length}</p>
        </Section>
      )}

      {storedResults.length > 0 && (
        <Section>
          <h3>Stored Profile Results for {selectedTable}</h3>
          <Table>
            <thead>
              <tr>
                <Th>Column</Th>
                <Th>Nulls %</Th>
                <Th>Unique Values</Th>
                <Th>Min/Max</Th>
              </tr>
            </thead>
            <tbody>
              {storedResults.map((result) => (
                <tr key={result.id}>
                  <Td>{result.column_name}</Td>
                  <Td>{result.result?.nulls?.null_percentage || 0}%</Td>
                  <Td>{result.result?.uniqueness?.unique_values || 'N/A'}</Td>
                  <Td>
                    {result.result?.statistics?.min !== undefined
                      ? `${result.result.statistics.min} - ${result.result.statistics.max}`
                      : 'N/A'}
                  </Td>
                </tr>
              ))}
            </tbody>
          </Table>
        </Section>
      )}
    </Container>
  );
};

export default DataProfiling;
