/**
 * DataProfilingPanel Component
 * Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
 */
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import PropTypes from 'prop-types';

const DataProfilingPanel = ({ theme }) => {
  const [tables, setTables] = useState([]);
  const [selectedTable, setSelectedTable] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [metrics, setMetrics] = useState(null);

  useEffect(() => {
    const fetchTables = async () => {
      try {
        const response = await axios.get('/api/profile/tables');
        setTables(response.data);
        setLoading(false);
      } catch (err) {
        setError(err.message);
        setLoading(false);
      }
    };

    fetchTables();
  }, []);

  const handleTableSelect = async (table) => {
    setSelectedTable(table);
    setError(null);
    try {
      const response = await axios.get(`/api/profile/${table}`);
      setMetrics(response.data);
    } catch (err) {
      setError(err.message);
    }
  };

  const themeStyles = {
    backgroundColor: theme === 'dark' ? '#1e1e1e' : '#ffffff',
    color: theme === 'dark' ? '#ffffff' : '#333333',
    padding: '20px',
    borderRadius: '8px',
  };

  const renderMetrics = () => {
    if (!metrics) return null;

    return (
      <div style={{ marginTop: '20px' }}>
        <h3>Profile for {selectedTable}</h3>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <tbody>
            <tr>
              <td style={{ padding: '8px', border: '1px solid #ddd' }}>Row Count</td>
              <td style={{ padding: '8px', border: '1px solid #ddd' }}>{metrics.rowCount || 'N/A'}</td>
            </tr>
            <tr>
              <td style={{ padding: '8px', border: '1px solid #ddd' }}>Column Count</td>
              <td style={{ padding: '8px', border: '1px solid #ddd' }}>{metrics.columnCount || 'N/A'}</td>
            </tr>
            {metrics.columns && metrics.columns.map((col, idx) => (
              <tr key={idx}>
                <td style={{ padding: '8px', border: '1px solid #ddd' }}>{col.name}</td>
                <td style={{ padding: '8px', border: '1px solid #ddd' }}>
                  Nulls: {col.nullPercent}%, Unique: {col.uniqueCount}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  };

  return (
    <div style={themeStyles}>
      <h2>Data Profiling</h2>

      {loading && <p>Loading tables...</p>}
      {error && <p style={{ color: 'red' }}>Error: {error}</p>}

      {!loading && !error && (
        <>
          <h3>Select a Table</h3>
          <ul style={{ listStyle: 'none', padding: 0 }}>
            {tables.map((table) => (
              <li
                key={table}
                onClick={() => handleTableSelect(table)}
                style={{
                  padding: '10px',
                  margin: '5px 0',
                  cursor: 'pointer',
                  backgroundColor: selectedTable === table
                    ? (theme === 'dark' ? '#3a3a3a' : '#e0e0e0')
                    : 'transparent',
                  borderRadius: '4px',
                }}
              >
                {table}
              </li>
            ))}
          </ul>

          {renderMetrics()}
        </>
      )}
    </div>
  );
};

DataProfilingPanel.propTypes = {
  theme: PropTypes.oneOf(['light', 'dark']).isRequired,
};

export default DataProfilingPanel;
