/**
 * LineageGraph Component - Visualize data lineage
 * Generated by: RTX 3050 (Qwen2.5-Coder-7B)
 */
import React, { useState } from 'react';
import { useLineage } from '../hooks';

const LineageGraph = ({ tableName }) => {
  const { lineageData, upstream, downstream, impactAnalysis, loading, error, getImpactAnalysis } = useLineage(tableName);
  const [showImpact, setShowImpact] = useState(false);

  const handleImpactAnalysis = async () => {
    await getImpactAnalysis();
    setShowImpact(true);
  };

  if (!tableName) {
    return <div className="p-4 text-gray-500">Select a table to view lineage</div>;
  }

  return (
    <div className="p-4 bg-white rounded-lg shadow">
      <h2 className="text-xl font-bold mb-4">Data Lineage: {tableName}</h2>

      {loading && <div className="text-blue-500">Loading lineage data...</div>}
      {error && <div className="text-red-500">Error: {error}</div>}

      <div className="flex flex-col items-center gap-4">
        {/* Upstream Tables */}
        <div className="flex flex-wrap gap-2 justify-center">
          {upstream.length > 0 ? (
            upstream.map((table, idx) => (
              <div key={idx} className="px-4 py-2 bg-gray-200 rounded-lg text-sm">
                {table.source_table || table}
              </div>
            ))
          ) : (
            <div className="text-gray-400 text-sm">No upstream tables</div>
          )}
        </div>

        {/* Arrow Down */}
        <div className="text-2xl text-gray-400">↓</div>

        {/* Current Table */}
        <div className="px-6 py-3 bg-blue-500 text-white rounded-lg font-semibold shadow-lg">
          {tableName}
        </div>

        {/* Arrow Down */}
        <div className="text-2xl text-gray-400">↓</div>

        {/* Downstream Tables */}
        <div className="flex flex-wrap gap-2 justify-center">
          {downstream.length > 0 ? (
            downstream.map((table, idx) => (
              <div key={idx} className="px-4 py-2 bg-green-200 rounded-lg text-sm">
                {table.target_table || table}
              </div>
            ))
          ) : (
            <div className="text-gray-400 text-sm">No downstream tables</div>
          )}
        </div>
      </div>

      <div className="mt-6">
        <button
          onClick={handleImpactAnalysis}
          disabled={loading}
          className="px-4 py-2 bg-orange-500 text-white rounded hover:bg-orange-600 disabled:bg-gray-400"
        >
          Analyze Impact
        </button>

        {showImpact && impactAnalysis && (
          <div className="mt-4 p-4 bg-orange-50 rounded">
            <h3 className="font-semibold mb-2">Impact Analysis</h3>
            <p><strong>Source:</strong> {impactAnalysis.source_table}</p>
            <p><strong>Affected Tables:</strong> {impactAnalysis.affected_tables?.length || 0}</p>
            <ul className="list-disc pl-6 mt-2">
              {impactAnalysis.affected_tables?.map((t, idx) => (
                <li key={idx}>{t.target_table} ({t.transformation_type})</li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
};

export default LineageGraph;
