/**
 * MultiTableSelector Component
 * V79 Enhancement: Multi-table selection for batch operations
 * Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
 */
import React, { useState, useEffect } from 'react';
import './MultiTableSelector.css';

const MultiTableSelector = ({ tables, selectedTables, onSelectionChange, disabled = false }) => {
  const [allSelected, setAllSelected] = useState(false);

  useEffect(() => {
    setAllSelected(selectedTables.length === tables.length && tables.length > 0);
  }, [selectedTables, tables]);

  const handleTableChange = (event) => {
    const tableName = event.target.value;
    const isChecked = event.target.checked;

    const updatedSelection = isChecked
      ? [...selectedTables, tableName]
      : selectedTables.filter(t => t !== tableName);

    onSelectionChange(updatedSelection);
  };

  const handleSelectAll = () => {
    if (allSelected) {
      onSelectionChange([]);
    } else {
      onSelectionChange([...tables]);
    }
  };

  const handleClearAll = () => {
    onSelectionChange([]);
  };

  return (
    <div className="multi-table-selector">
      <div className="selector-header">
        <h4>Select Tables</h4>
        <span className="selected-count">
          {selectedTables.length} of {tables.length} selected
        </span>
      </div>

      <div className="selector-actions">
        <button
          onClick={handleSelectAll}
          className="select-all-btn"
          disabled={disabled}
        >
          {allSelected ? 'Deselect All' : 'Select All'}
        </button>
        {selectedTables.length > 0 && (
          <button
            onClick={handleClearAll}
            className="clear-btn"
            disabled={disabled}
          >
            Clear Selection
          </button>
        )}
      </div>

      <div className="table-checkboxes">
        {tables.map(table => (
          <label key={table} className={`table-checkbox ${selectedTables.includes(table) ? 'selected' : ''}`}>
            <input
              type="checkbox"
              value={table}
              checked={selectedTables.includes(table)}
              onChange={handleTableChange}
              disabled={disabled}
            />
            <span className="table-name">{table}</span>
          </label>
        ))}
      </div>

      {selectedTables.length > 0 && (
        <div className="selected-preview">
          <strong>Selected:</strong> {selectedTables.join(', ')}
        </div>
      )}
    </div>
  );
};

export default MultiTableSelector;
