/**
 * ReportsPanel Component - Generate and view reports
 * Generated by: RTX 3050 (Qwen2.5-Coder-7B)
 */
import React, { useState } from 'react';
import { useReports } from '../hooks';

const ReportsPanel = ({ tableName }) => {
  const { templates, reportData, loading, error, generateReport } = useReports();
  const [reportType, setReportType] = useState('dq_summary');
  const [reportFormat, setReportFormat] = useState('json');

  const handleGenerate = async () => {
    await generateReport(reportType, reportFormat, tableName);
  };

  return (
    <div className="p-4 bg-white rounded-lg shadow">
      <h2 className="text-xl font-bold mb-4">Reports</h2>

      <div className="grid grid-cols-2 gap-4 mb-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Report Type</label>
          <select
            value={reportType}
            onChange={(e) => setReportType(e.target.value)}
            className="w-full p-2 border rounded focus:ring-2 focus:ring-indigo-500"
          >
            {templates.map((t) => (
              <option key={t.template_id} value={t.template_id}>{t.name}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Format</label>
          <select
            value={reportFormat}
            onChange={(e) => setReportFormat(e.target.value)}
            className="w-full p-2 border rounded focus:ring-2 focus:ring-indigo-500"
          >
            <option value="json">JSON</option>
            <option value="html">HTML</option>
          </select>
        </div>
      </div>

      <button
        onClick={handleGenerate}
        disabled={loading}
        className="px-4 py-2 bg-indigo-600 text-white rounded hover:bg-indigo-700 disabled:bg-gray-400"
      >
        {loading ? 'Generating...' : 'Generate Report'}
      </button>

      {error && <div className="text-red-500 mt-4">Error: {error}</div>}

      {reportData && (
        <div className="mt-4">
          <h3 className="text-lg font-semibold mb-2">Report Output</h3>
          {reportData.format === 'html' ? (
            <div
              className="p-4 border rounded bg-gray-50"
              dangerouslySetInnerHTML={{ __html: reportData.content }}
            />
          ) : (
            <pre className="p-4 bg-gray-800 text-green-400 rounded overflow-auto max-h-96">
              {JSON.stringify(reportData.content, null, 2)}
            </pre>
          )}
        </div>
      )}
    </div>
  );
};

export default ReportsPanel;
