/**
 * RootCauseAnalysis Component - V83 Fix
 * Fixed API paths to match backend routes
 * Generated by RTX 3050 with RTX 5090 architecture guidance
 */
import React, { useState, useEffect } from 'react';
import styled from 'styled-components';

const Container = styled.div`
  background-color: #121212;
  color: #ffffff;
  padding: 20px;
`;

const Section = styled.div`
  margin-bottom: 20px;
  padding: 15px;
  background-color: #1e1e1e;
  border-radius: 8px;
`;

const Button = styled.button`
  background-color: #007bff;
  color: #ffffff;
  border: none;
  padding: 8px 16px;
  cursor: pointer;
  border-radius: 4px;
  margin-right: 10px;

  &:disabled {
    background-color: #555;
    cursor: not-allowed;
  }

  &.secondary {
    background-color: #6c757d;
  }

  &.primary {
    background-color: #28a745;
  }
`;

const Table = styled.table`
  width: 100%;
  border-collapse: collapse;
  margin-top: 15px;
`;

const Th = styled.th`
  background-color: #333333;
  color: #ffffff;
  padding: 10px;
  text-align: left;
`;

const Td = styled.td`
  border: 1px solid #444444;
  padding: 10px;
`;

const AnalysisCard = styled.div`
  padding: 15px;
  background: linear-gradient(135deg, #1a2a3a 0%, #1e1e1e 100%);
  border-radius: 8px;
  margin-bottom: 15px;
  border-left: 4px solid #007bff;
`;

const Confidence = styled.span`
  padding: 4px 8px;
  border-radius: 4px;
  font-size: 12px;
  font-weight: bold;

  &.high { background-color: #28a745; }
  &.medium { background-color: #ffc107; color: #000; }
  &.low { background-color: #dc3545; }
`;

const EmptyState = styled.p`
  color: #888;
  font-style: italic;
  text-align: center;
  padding: 20px;
`;

const RootCauseAnalysis = () => {
  const [failedResults, setFailedResults] = useState([]);
  const [analyses, setAnalyses] = useState([]);
  const [loading, setLoading] = useState(false);
  const [analyzing, setAnalyzing] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    loadFailedResults();
    loadAnalyses();
  }, []);

  // V83 Fix: Corrected API path from /api/dq/results to /data-quality/results
  const loadFailedResults = async () => {
    try {
      const res = await fetch('/data-quality/results');
      const data = await res.json();
      setFailedResults(data.filter(r => !r.passed));
    } catch (err) {
      console.error('Failed to load results:', err);
      setError('Failed to load DQ results');
    }
  };

  // V83 Fix: Corrected API path from /api/ai-analysis/analyses to /ai-analysis/analyze
  const loadAnalyses = async () => {
    try {
      // Local AI uses /ai-analysis/analyze for getting insights
      const res = await fetch('/data-quality/results');
      const data = await res.json();
      // Filter for results that have been analyzed (have analysis data)
      const analyzed = data.filter(r => r.analysis);
      setAnalyses(analyzed);
    } catch (err) {
      console.error('Failed to load analyses:', err);
    }
  };

  // V83 Fix: Use correct endpoint for AI analysis
  const analyzeFailure = async (resultId, tableName) => {
    setAnalyzing(resultId);
    setLoading(true);
    setError(null);
    try {
      // Local AI uses /ai-analysis/insights/{table_name} endpoint
      const res = await fetch(`/ai-analysis/insights/${tableName}`, {
        method: 'GET'
      });

      if (!res.ok) {
        throw new Error(`Analysis failed: ${res.status}`);
      }

      const data = await res.json();
      alert(`Analysis complete!\n\nInsights: ${JSON.stringify(data.insights || data, null, 2)}`);
      loadAnalyses();
    } catch (err) {
      console.error('Analysis failed:', err);
      setError('Analysis failed: ' + err.message);
    } finally {
      setLoading(false);
      setAnalyzing(null);
    }
  };

  // Batch analyze using anomaly detection
  const batchAnalyze = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/ai-analysis/anomalies/detect', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({})
      });

      if (!res.ok) {
        throw new Error(`Batch analysis failed: ${res.status}`);
      }

      const data = await res.json();
      alert(`Batch analysis complete! Found ${data.anomalies?.length || 0} anomalies.`);
      loadAnalyses();
    } catch (err) {
      console.error('Batch analysis failed:', err);
      setError('Batch analysis failed: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container>
      <h2>Root Cause Analysis</h2>
      <p style={{ color: '#888' }}>AI-powered analysis using LOCAL models (RTX 5090)</p>

      {error && (
        <Section style={{ borderLeft: '4px solid #dc3545' }}>
          <p style={{ color: '#ff6b6b' }}>{error}</p>
        </Section>
      )}

      <Section>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' }}>
          <h3>Failed DQ Results ({failedResults.length})</h3>
          <Button
            onClick={batchAnalyze}
            disabled={loading || failedResults.length === 0}
            className="primary"
          >
            {loading ? 'Analyzing...' : '🤖 Batch Analyze'}
          </Button>
        </div>

        {failedResults.length === 0 ? (
          <EmptyState>No failed results to analyze. Run some data quality rules first!</EmptyState>
        ) : (
          <Table>
            <thead>
              <tr>
                <Th>Rule</Th>
                <Th>Table</Th>
                <Th>Failed Count</Th>
                <Th>Pass Rate</Th>
                <Th>Actions</Th>
              </tr>
            </thead>
            <tbody>
              {failedResults.map(r => (
                <tr key={r.id}>
                  <Td>{r.rule_name || r.name || 'Unknown Rule'}</Td>
                  <Td>{r.table_name || r.table || 'Unknown'}</Td>
                  <Td style={{ color: '#ff6b6b' }}>{r.failed_count}</Td>
                  <Td>{r.pass_rate || ((r.total_count - r.failed_count) / r.total_count * 100).toFixed(1)}%</Td>
                  <Td>
                    <Button
                      onClick={() => analyzeFailure(r.id, r.table_name || r.table)}
                      disabled={loading}
                    >
                      {analyzing === r.id ? '🔄 Analyzing...' : '🔍 Analyze'}
                    </Button>
                  </Td>
                </tr>
              ))}
            </tbody>
          </Table>
        )}
      </Section>

      <Section>
        <h3>AI Analyses ({analyses.length})</h3>
        {analyses.length === 0 ? (
          <EmptyState>No analyses yet. Click "Analyze" on a failed result above.</EmptyState>
        ) : (
          <div>
            {analyses.map(a => (
              <AnalysisCard key={a.id}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
                  <strong>{a.rule_name || a.name}</strong>
                  <Confidence className={
                    (a.confidence_score || 0.5) > 0.7 ? 'high' :
                    (a.confidence_score || 0.5) > 0.4 ? 'medium' : 'low'
                  }>
                    {((a.confidence_score || 0.5) * 100).toFixed(0)}% confident
                  </Confidence>
                </div>
                <div>
                  <h4 style={{ marginBottom: '5px' }}>Root Cause</h4>
                  <p>{a.analysis?.cause || a.analysis || 'Analysis pending'}</p>
                </div>
                {a.analysis?.remediation && (
                  <div style={{ marginTop: '10px' }}>
                    <h4 style={{ marginBottom: '5px' }}>Remediation Steps</h4>
                    <ol style={{ margin: 0, paddingLeft: '20px' }}>
                      {a.analysis.remediation.map((r, i) => <li key={i}>{r}</li>)}
                    </ol>
                  </div>
                )}
              </AnalysisCard>
            ))}
          </div>
        )}
      </Section>
    </Container>
  );
};

export default RootCauseAnalysis;
