/**
 * TableBrowser Component
 * Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
 */
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import PropTypes from 'prop-types';

const TableBrowser = ({ theme, onTableSelect }) => {
  const [tables, setTables] = useState([]);
  const [filteredTables, setFilteredTables] = useState([]);
  const [selectedTable, setSelectedTable] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [hoveredTable, setHoveredTable] = useState(null);
  const [tableDetails, setTableDetails] = useState({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchTables = async () => {
      try {
        const response = await axios.get('/api/profile/tables');
        setTables(response.data);
        setFilteredTables(response.data);
        setLoading(false);
      } catch (err) {
        setError(err.message);
        setLoading(false);
      }
    };

    fetchTables();
  }, []);

  const handleSearch = (event) => {
    const term = event.target.value.toLowerCase();
    setSearchTerm(term);
    const filtered = tables.filter((table) =>
      table.toLowerCase().includes(term)
    );
    setFilteredTables(filtered);
  };

  const handleTableHover = async (table) => {
    setHoveredTable(table);
    if (!tableDetails[table]) {
      try {
        const response = await axios.get(`/api/profile/${table}`);
        setTableDetails((prev) => ({ ...prev, [table]: response.data }));
      } catch (err) {
        console.error('Error fetching table details:', err);
      }
    }
  };

  const handleTableSelect = (table) => {
    setSelectedTable(table);
    if (onTableSelect) {
      onTableSelect(table);
    }
  };

  const themeStyles = {
    backgroundColor: theme === 'dark' ? '#1e1e1e' : '#ffffff',
    color: theme === 'dark' ? '#ffffff' : '#333333',
    padding: '20px',
    borderRadius: '8px',
  };

  return (
    <div style={themeStyles}>
      <h2>Table Browser</h2>

      {/* Search Input */}
      <input
        type="text"
        placeholder="Search tables..."
        value={searchTerm}
        onChange={handleSearch}
        style={{
          width: '100%',
          padding: '10px',
          marginBottom: '15px',
          borderRadius: '4px',
          border: '1px solid #ccc',
          backgroundColor: theme === 'dark' ? '#2d2d2d' : '#fff',
          color: theme === 'dark' ? '#fff' : '#333',
        }}
      />

      {loading && <p>Loading tables...</p>}
      {error && <p style={{ color: 'red' }}>Error: {error}</p>}

      {/* Table List */}
      {!loading && !error && (
        <ul style={{ listStyle: 'none', padding: 0 }}>
          {filteredTables.map((table) => (
            <li
              key={table}
              onMouseEnter={() => handleTableHover(table)}
              onMouseLeave={() => setHoveredTable(null)}
              onClick={() => handleTableSelect(table)}
              style={{
                padding: '10px',
                margin: '5px 0',
                cursor: 'pointer',
                backgroundColor:
                  selectedTable === table
                    ? theme === 'dark'
                      ? '#3a3a3a'
                      : '#e0e0e0'
                    : hoveredTable === table
                    ? theme === 'dark'
                      ? '#2a2a2a'
                      : '#f0f0f0'
                    : 'transparent',
                borderRadius: '4px',
                position: 'relative',
              }}
            >
              {table}

              {/* Hover Tooltip */}
              {hoveredTable === table && tableDetails[table] && (
                <div
                  style={{
                    position: 'absolute',
                    left: '100%',
                    top: 0,
                    marginLeft: '10px',
                    padding: '10px',
                    backgroundColor: theme === 'dark' ? '#333' : '#fff',
                    border: '1px solid #ccc',
                    borderRadius: '4px',
                    zIndex: 1000,
                    minWidth: '200px',
                    boxShadow: '0 2px 10px rgba(0,0,0,0.2)',
                  }}
                >
                  <strong>{table}</strong>
                  <p>Rows: {tableDetails[table].rowCount || 'N/A'}</p>
                  <p>Columns: {tableDetails[table].columnCount || 'N/A'}</p>
                </div>
              )}
            </li>
          ))}
        </ul>
      )}

      {filteredTables.length === 0 && !loading && (
        <p>No tables found matching "{searchTerm}"</p>
      )}
    </div>
  );
};

TableBrowser.propTypes = {
  theme: PropTypes.oneOf(['light', 'dark']).isRequired,
  onTableSelect: PropTypes.func,
};

TableBrowser.defaultProps = {
  onTableSelect: null,
};

export default TableBrowser;
