"""
Retry Logic Module with Exponential Backoff
Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
"""
import time
import asyncio
import logging
from typing import Callable, Any, Type, Tuple, Union
from functools import wraps

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def retry(
    exceptions: Union[Type[Exception], Tuple[Type[Exception], ...]] = Exception,
    max_retries: int = 3,
    base_delay: float = 1.0,
    max_delay: float = 30.0,
) -> Callable[[Callable[..., Any]], Callable[..., Any]]:
    """
    Retry decorator with exponential backoff.

    Args:
        exceptions: Exception types to retry on
        max_retries: Maximum number of retry attempts
        base_delay: Base delay in seconds
        max_delay: Maximum delay in seconds

    Returns:
        Decorated function with retry logic
    """
    def decorator(func: Callable[..., Any]) -> Callable[..., Any]:
        @wraps(func)
        def sync_wrapper(*args: Any, **kwargs: Any) -> Any:
            retries = 0
            while retries < max_retries:
                try:
                    return func(*args, **kwargs)
                except exceptions as e:
                    retries += 1
                    if retries >= max_retries:
                        logger.error(f"Max retries reached for {func.__name__}: {e}")
                        raise
                    delay = min(base_delay * (2 ** retries), max_delay)
                    logger.info(f"Retrying {func.__name__} in {delay:.2f}s (attempt {retries}/{max_retries})")
                    time.sleep(delay)
            return None

        @wraps(func)
        async def async_wrapper(*args: Any, **kwargs: Any) -> Any:
            retries = 0
            while retries < max_retries:
                try:
                    return await func(*args, **kwargs)
                except exceptions as e:
                    retries += 1
                    if retries >= max_retries:
                        logger.error(f"Max retries reached for {func.__name__}: {e}")
                        raise
                    delay = min(base_delay * (2 ** retries), max_delay)
                    logger.info(f"Retrying {func.__name__} in {delay:.2f}s (attempt {retries}/{max_retries})")
                    await asyncio.sleep(delay)
            return None

        # Return appropriate wrapper based on function type
        if asyncio.iscoroutinefunction(func):
            return async_wrapper
        return sync_wrapper

    return decorator
