/**
 * useAIAnalysis Hook - AI-powered data analysis
 * Generated by: RTX 3050 (Qwen2.5-Coder-7B)
 */
import { useState, useEffect } from 'react';
import { apiCall } from './useApi';

const useAIAnalysis = (tableName) => {
  const [insights, setInsights] = useState(null);
  const [anomalies, setAnomalies] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const analyzeProfile = async (profileData) => {
    setLoading(true);
    setError(null);
    try {
      const response = await apiCall('/ai-analysis/analyze', {
        method: 'POST',
        body: JSON.stringify({ profile_data: profileData }),
      });
      setInsights(response);
      return response;
    } catch (err) {
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  };

  const detectAnomalies = async (tableStats) => {
    setLoading(true);
    setError(null);
    try {
      const response = await apiCall('/ai-analysis/anomalies/detect', {
        method: 'POST',
        body: JSON.stringify({ table_stats: tableStats }),
      });
      setAnomalies(response);
      return response;
    } catch (err) {
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    setInsights(null);
    setAnomalies(null);
    setError(null);
  }, [tableName]);

  return { insights, anomalies, loading, error, analyzeProfile, detectAnomalies };
};

export default useAIAnalysis;
