/**
 * useDataProfiling Hook - Fetch profiling data for tables
 * Generated by: RTX 3050 (Qwen2.5-Coder-7B)
 */
import { useState, useEffect, useCallback } from 'react';
import { apiCall } from './useApi';

const useDataProfiling = (tableName) => {
  const [profilingData, setProfilingData] = useState(null);
  const [tables, setTables] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchTables = useCallback(async () => {
    try {
      const data = await apiCall('/data-profiling/tables');
      setTables(data.tables || []);
    } catch (err) {
      setError(err.message);
    }
  }, []);

  const fetchProfilingData = useCallback(async () => {
    if (!tableName) return;
    setLoading(true);
    setError(null);
    try {
      const data = await apiCall(`/data-profiling/profile/${tableName}`);
      setProfilingData(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, [tableName]);

  useEffect(() => {
    fetchTables();
  }, [fetchTables]);

  useEffect(() => {
    if (tableName) {
      fetchProfilingData();
    }
  }, [tableName, fetchProfilingData]);

  const refetch = () => {
    fetchProfilingData();
  };

  return { profilingData, tables, loading, error, refetch };
};

export default useDataProfiling;
