/**
 * useDataQuality Hook - Manage DQ rules CRUD operations
 * Generated by: RTX 3050 (Qwen2.5-Coder-7B)
 */
import { useState, useCallback, useEffect } from 'react';
import { apiCall } from './useApi';

const useDataQuality = () => {
  const [rules, setRules] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const fetchRules = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await apiCall('/data-quality/rules');
      setRules(data.rules || []);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchRules();
  }, [fetchRules]);

  const addRule = useCallback(async (rule) => {
    setLoading(true);
    try {
      const data = await apiCall('/data-quality/rules/custom', {
        method: 'POST',
        body: JSON.stringify(rule),
      });
      setRules(prev => [...prev, data]);
      return data;
    } catch (err) {
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  }, []);

  const updateRule = useCallback(async (id, updatedRule) => {
    setLoading(true);
    try {
      const data = await apiCall(`/data-quality/rules/${id}`, {
        method: 'PUT',
        body: JSON.stringify(updatedRule),
      });
      setRules(prev => prev.map(rule => rule.id === id ? data : rule));
      return data;
    } catch (err) {
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  }, []);

  const deleteRule = useCallback(async (id) => {
    setLoading(true);
    try {
      await apiCall(`/data-quality/rules/${id}`, { method: 'DELETE' });
      setRules(prev => prev.filter(rule => rule.id !== id));
    } catch (err) {
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  }, []);

  const toggleRule = useCallback(async (id) => {
    setLoading(true);
    try {
      const data = await apiCall(`/data-quality/rules/${id}/toggle`, { method: 'PATCH' });
      setRules(prev => prev.map(rule => rule.id === id ? data : rule));
      return data;
    } catch (err) {
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  }, []);

  return { rules, loading, error, fetchRules, addRule, updateRule, deleteRule, toggleRule };
};

export default useDataQuality;
