/**
 * useLineage Hook - Data lineage tracking
 * Generated by: RTX 3050 (Qwen2.5-Coder-7B)
 */
import { useState, useEffect, useCallback } from 'react';
import { apiCall } from './useApi';

const useLineage = (tableName) => {
  const [lineageData, setLineageData] = useState(null);
  const [upstream, setUpstream] = useState([]);
  const [downstream, setDownstream] = useState([]);
  const [impactAnalysis, setImpactAnalysis] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const fetchLineage = useCallback(async () => {
    if (!tableName) return;
    setLoading(true);
    setError(null);
    try {
      const [lineage, upstreamData, downstreamData] = await Promise.all([
        apiCall(`/lineage/table/${tableName}`),
        apiCall(`/lineage/upstream/${tableName}`),
        apiCall(`/lineage/downstream/${tableName}`),
      ]);
      setLineageData(lineage);
      setUpstream(upstreamData.upstream || []);
      setDownstream(downstreamData.downstream || []);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, [tableName]);

  const getImpactAnalysis = useCallback(async () => {
    if (!tableName) return null;
    setLoading(true);
    try {
      const impact = await apiCall(`/lineage/impact/${tableName}`);
      setImpactAnalysis(impact);
      return impact;
    } catch (err) {
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  }, [tableName]);

  useEffect(() => {
    if (tableName) {
      fetchLineage();
    }
  }, [tableName, fetchLineage]);

  return { lineageData, upstream, downstream, impactAnalysis, loading, error, fetchLineage, getImpactAnalysis };
};

export default useLineage;
