/**
 * useReports Hook - Report generation
 * Generated by: RTX 3050 (Qwen2.5-Coder-7B)
 */
import { useState, useEffect, useCallback } from 'react';
import { apiCall } from './useApi';

const useReports = () => {
  const [templates, setTemplates] = useState([]);
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const fetchTemplates = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await apiCall('/reports/templates');
      setTemplates(response.templates || []);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  const generateReport = useCallback(async (reportType, outputFormat, tableName, data = {}) => {
    setLoading(true);
    setError(null);
    try {
      const response = await apiCall('/reports/generate', {
        method: 'POST',
        body: JSON.stringify({
          report_type: reportType,
          output_format: outputFormat,
          table_name: tableName,
          data,
        }),
      });
      setReportData(response);
      return response;
    } catch (err) {
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  }, []);

  const getSummary = useCallback(async (tableName = null) => {
    setLoading(true);
    try {
      const url = tableName ? `/reports/summary?table_name=${tableName}` : '/reports/summary';
      const response = await apiCall(url);
      return response;
    } catch (err) {
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchTemplates();
  }, [fetchTemplates]);

  return { templates, reportData, loading, error, fetchTemplates, generateReport, getSummary };
};

export default useReports;
