"""
Integration tests for DQM LOCAL AI application.
Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
"""
import pytest
from httpx import AsyncClient
from app.main import app

@pytest.fixture
async def client():
    async with AsyncClient(app=app, base_url="http://test") as client:
        yield client

@pytest.mark.asyncio
async def test_valid_table_profiling(client):
    """Test that valid tables return profile data."""
    response = await client.get("/api/profile/tables")
    assert response.status_code == 200
    assert isinstance(response.json(), list)

@pytest.mark.asyncio
async def test_invalid_table_rejection(client):
    """Security test: Invalid tables should be rejected."""
    response = await client.get("/api/profile/non_existent_table")
    assert response.status_code == 400  # Should reject non-whitelisted tables
    assert "not in the whitelist" in response.json().get("detail", "").lower()

@pytest.mark.asyncio
async def test_create_rule(client):
    """Test rule creation endpoint."""
    rule_data = {"name": "test_rule", "description": "Test rule", "condition": "column > 10"}
    response = await client.post("/api/rules", json=rule_data)
    assert response.status_code == 201
    created_rule = response.json()
    assert created_rule["name"] == "test_rule"
    assert created_rule["description"] == "Test rule"
    assert created_rule["condition"] == "column > 10"

@pytest.mark.asyncio
async def test_list_rules(client):
    """Test listing all rules."""
    response = await client.get("/api/rules")
    assert response.status_code == 200
    assert isinstance(response.json(), list)

@pytest.mark.asyncio
async def test_delete_rule(client):
    """Test rule deletion endpoint."""
    # First, create a rule to delete
    rule_data = {"name": "test_rule_to_delete", "description": "Test rule to delete", "condition": "column > 20"}
    response = await client.post("/api/rules", json=rule_data)
    created_rule = response.json()
    rule_id = created_rule["id"]

    # Now, delete the rule
    response = await client.delete(f"/api/rules/{rule_id}")
    assert response.status_code == 204

@pytest.mark.asyncio
async def test_execute_rule(client):
    """Test rule execution endpoint."""
    # First, create a rule to execute
    rule_data = {"name": "test_rule_to_execute", "description": "Test rule to execute", "condition": "column > 30"}
    response = await client.post("/api/rules", json=rule_data)
    created_rule = response.json()
    rule_id = created_rule["id"]

    # Now, execute the rule
    response = await client.post(f"/api/rules/{rule_id}/execute")
    assert response.status_code == 200
    result = response.json()
    assert "rule_id" in result

@pytest.mark.asyncio
async def test_ai_root_cause_analysis(client):
    """Test AI analysis endpoint."""
    analysis_data = {"issue": "Data discrepancy in orders table"}
    response = await client.post("/api/analysis/ai", json=analysis_data)
    assert response.status_code == 200
    assert isinstance(response.json(), dict)
    assert "analysis" in response.json()
