"""
Cache Service - In-memory caching with TTL support
Generated by: RTX 3050 (Qwen2.5-Coder-7B)
"""
import asyncio
from typing import Any, Optional
import time
import fnmatch

# Singleton cache instance
_cache_service: Optional["CacheService"] = None


class CacheService:
    """In-memory cache with TTL support and async operations."""

    def __init__(self):
        self._cache: dict[str, tuple[Any, float]] = {}
        self._lock = asyncio.Lock()

    async def get(self, key: str) -> Optional[Any]:
        """Get value from cache if not expired."""
        async with self._lock:
            if key not in self._cache:
                return None
            value, expires = self._cache[key]
            if time.time() > expires:
                del self._cache[key]
                return None
            return value

    async def set(self, key: str, value: Any, ttl_seconds: int = 3600) -> None:
        """Set value in cache with TTL."""
        async with self._lock:
            self._cache[key] = (value, time.time() + ttl_seconds)

    async def delete(self, key: str) -> bool:
        """Delete key from cache."""
        async with self._lock:
            if key in self._cache:
                del self._cache[key]
                return True
            return False

    async def clear_pattern(self, pattern: str) -> int:
        """Clear all keys matching pattern (supports wildcards)."""
        async with self._lock:
            keys_to_delete = [k for k in self._cache if fnmatch.fnmatch(k, pattern)]
            for key in keys_to_delete:
                del self._cache[key]
            return len(keys_to_delete)

    async def clear_all(self) -> None:
        """Clear entire cache."""
        async with self._lock:
            self._cache.clear()

    async def stats(self) -> dict:
        """Get cache statistics."""
        async with self._lock:
            now = time.time()
            expired = sum(1 for _, (_, exp) in self._cache.items() if now > exp)
            return {
                "total_keys": len(self._cache),
                "expired_keys": expired,
                "active_keys": len(self._cache) - expired
            }


async def get_cache_service() -> CacheService:
    """Get or create singleton cache service."""
    global _cache_service
    if _cache_service is None:
        _cache_service = CacheService()
    return _cache_service
