"""
Data Quality Rules Service - Fixed asyncpg usage
Generated by RTX 5090 (Qwen2.5-Coder-32B-Instruct-AWQ)
"""
import asyncpg
from typing import List, Dict, Any


class DataQualityRulesService:
    """Service for managing data quality rules."""

    def __init__(self, dsn: str):
        self.dsn = dsn

    async def suggest_rules(self, profiling_results: List[Dict]) -> List[Dict]:
        """Suggest data quality rules based on profiling results."""
        suggested_rules = []
        for result in profiling_results:
            null_pct = result.get('null_percentage', 0)
            if null_pct and null_pct > 0.1:
                suggested_rules.append({
                    'name': f"{result.get('table', 'unknown')}_{result.get('column', 'unknown')}_null_check",
                    'table': result.get('table', ''),
                    'column': result.get('column', ''),
                    'rule_type': 'null_check',
                    'definition': f"SELECT COUNT(*) FROM {result.get('table', '')} WHERE {result.get('column', '')} IS NULL",
                    'severity': 'medium'
                })
        return suggested_rules

    async def create_rule(self, name: str, table: str, column: str, rule_type: str, definition: str, severity: str):
        """Create a new data quality rule."""
        conn = await asyncpg.connect(self.dsn)
        try:
            await conn.execute('''
                INSERT INTO data_quality_rules (name, table_name, column_name, rule_type, definition, severity)
                VALUES ($1, $2, $3, $4, $5, $6)
            ''', name, table, column, rule_type, definition, severity)
        finally:
            await conn.close()

    async def execute_rule(self, rule_id: int) -> Dict[str, Any]:
        """Execute a data quality rule and store results."""
        conn = await asyncpg.connect(self.dsn)
        try:
            rule = await conn.fetchrow('SELECT * FROM data_quality_rules WHERE id = $1', rule_id)
            if not rule:
                return {"error": "Rule not found"}
            query = rule['definition']
            failures = await conn.fetch(query)
            await conn.execute('''
                INSERT INTO data_quality_results (rule_id, failures)
                VALUES ($1, $2)
            ''', rule_id, str(failures))
            return {"rule_id": rule_id, "executed": True, "failure_count": len(failures)}
        finally:
            await conn.close()

    async def get_all_rules(self) -> List[Dict]:
        """Get all active data quality rules."""
        conn = await asyncpg.connect(self.dsn)
        try:
            # First check if table exists
            table_exists = await conn.fetchval('''
                SELECT EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_name = 'data_quality_rules'
                )
            ''')
            if not table_exists:
                return []
            rules = await conn.fetch('SELECT * FROM data_quality_rules')
            return [dict(rule) for rule in rules]
        except Exception:
            return []
        finally:
            await conn.close()

    async def get_failures(self, rule_id: int) -> List[str]:
        """Get failures for a specific rule."""
        conn = await asyncpg.connect(self.dsn)
        try:
            table_exists = await conn.fetchval('''
                SELECT EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_name = 'data_quality_results'
                )
            ''')
            if not table_exists:
                return []
            failures = await conn.fetch('SELECT failures FROM data_quality_results WHERE rule_id = $1', rule_id)
            return [str(failure['failures']) for failure in failures]
        except Exception:
            return []
        finally:
            await conn.close()
