"""
Routes Package - Domain-Separated Routes
Generated by LOCAL AI (RTX 5090 + RTX 3050)
Enhanced by Expert AI (Claude Opus 4.5) - V74, V76, V77
"""
from .data_profiling import router as data_profiling_router
from .data_quality import router as data_quality_router
from .ai_analysis import router as ai_analysis_router
from .database import router as database_router
from .audit import router as audit_router
from .lineage import router as lineage_router
from .reports import router as reports_router

__all__ = [
    "data_profiling_router",
    "data_quality_router",
    "ai_analysis_router",
    "database_router",
    "audit_router",
    "lineage_router",
    "reports_router",
]
