"""
Routes Package - Domain-Separated Routes
Generated by LOCAL AI (RTX 5090 + RTX 3050)
"""
from .data_profiling import router as data_profiling_router
from .data_quality import router as data_quality_router
from .ai_analysis import router as ai_analysis_router

__all__ = [
    "data_profiling_router",
    "data_quality_router",
    "ai_analysis_router",
]
