"""
AI Analysis Routes - Enhanced
Generated by: RTX 3050 (skeleton), Expert AI (enhancement)
"""
from fastapi import APIRouter, HTTPException, Query
from typing import Optional, Dict, Any
from pydantic import BaseModel

from app.services.ai_analysis_service import get_ai_analysis_service
from app.services.data_profiling_service import get_profiling_service

router = APIRouter(
    prefix="/ai-analysis",
    tags=["AI Analysis"]
)


class AnalysisRequest(BaseModel):
    table_name: Optional[str] = None
    include_anomalies: bool = True


class AnomalyRequest(BaseModel):
    tables: Optional[list] = None


@router.post("/analyze")
async def analyze_data_quality(request: AnalysisRequest):
    """Analyze data quality using AI-powered analysis."""
    try:
        ai_service = await get_ai_analysis_service()
        profiling_service = await get_profiling_service()
        
        # Get profiling data
        if request.table_name:
            profile = await profiling_service.profile_table(request.table_name)
            profile_data = profile.dict() if hasattr(profile, 'dict') else profile
        else:
            tables = await profiling_service.get_tables()
            profile_data = {"tables": tables[:5]}  # Limit for demo
        
        # Analyze
        result = await ai_service.analyze_profile(profile_data)
        
        return {
            "status": "success",
            "analysis": result
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/anomalies/detect")
async def detect_anomalies(request: AnomalyRequest):
    """Detect anomalies in data quality metrics."""
    try:
        ai_service = await get_ai_analysis_service()
        profiling_service = await get_profiling_service()
        
        # Build table stats
        tables = request.tables or await profiling_service.get_tables()
        table_stats = {}
        for table in tables[:10]:  # Limit
            try:
                count = await profiling_service.get_row_count(table)
                table_stats[table] = {"row_count": count, "total_columns": 10}
            except:
                continue
        
        anomalies = await ai_service.detect_anomalies(table_stats)
        
        return {
            "status": "success",
            "anomalies": anomalies,
            "tables_analyzed": len(table_stats)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/insights/{table_name}")
async def get_table_insights(table_name: str):
    """Get AI-generated insights for a specific table."""
    try:
        ai_service = await get_ai_analysis_service()
        profiling_service = await get_profiling_service()
        
        profile = await profiling_service.profile_table(table_name)
        profile_data = profile.dict() if hasattr(profile, 'dict') else {"table_name": table_name, "columns": [], "row_count": 0}
        
        result = await ai_service.analyze_profile(profile_data)
        
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
