"""
Azure AD Authentication Routes
Generated by RTX 3050, enhanced by Expert

Routes:
- GET /auth/login - Redirect to Azure AD login
- GET /auth/callback - Handle OAuth callback
- POST /auth/token/refresh - Refresh access token
- GET /auth/me - Get current user info
"""
from fastapi import APIRouter, Request, Depends, HTTPException
from fastapi.responses import RedirectResponse
from typing import Optional
import secrets

from app.services.azure_auth import (
    AzureAuthService,
    get_azure_settings,
    get_current_user,
    require_auth,
    UserInfo,
    TokenResponse,
)

router = APIRouter(prefix="/auth", tags=["Authentication"])


@router.get("/login")
async def login(request: Request):
    """
    Redirect to Azure AD login page.

    Initiates OAuth 2.0 authorization code flow.
    """
    settings = get_azure_settings()

    if not settings.AZURE_AUTH_ENABLED:
        raise HTTPException(
            status_code=400,
            detail="Azure authentication is not enabled"
        )

    # Generate state for CSRF protection
    state = secrets.token_urlsafe(32)
    # In production, store state in session/Redis

    service = AzureAuthService(settings)
    auth_url = service.get_authorization_url(state=state)

    return RedirectResponse(url=auth_url)


@router.get("/callback")
async def callback(
    code: Optional[str] = None,
    state: Optional[str] = None,
    error: Optional[str] = None,
    error_description: Optional[str] = None,
):
    """
    Handle OAuth callback from Azure AD.

    Exchanges authorization code for tokens.
    """
    if error:
        raise HTTPException(
            status_code=400,
            detail=f"OAuth error: {error} - {error_description}"
        )

    if not code:
        raise HTTPException(
            status_code=400,
            detail="No authorization code provided"
        )

    # In production, validate state against stored value

    settings = get_azure_settings()
    service = AzureAuthService(settings)

    tokens = await service.exchange_code_for_tokens(code)

    # Return tokens (in production, set as HTTP-only cookies)
    return {
        "access_token": tokens.access_token,
        "token_type": tokens.token_type,
        "expires_in": tokens.expires_in,
        "refresh_token": tokens.refresh_token,
    }


@router.post("/token/refresh", response_model=TokenResponse)
async def refresh_token(refresh_token: str):
    """
    Refresh access token using refresh token.
    """
    settings = get_azure_settings()

    if not settings.AZURE_AUTH_ENABLED:
        raise HTTPException(
            status_code=400,
            detail="Azure authentication is not enabled"
        )

    service = AzureAuthService(settings)
    return await service.refresh_access_token(refresh_token)


@router.get("/me", response_model=UserInfo)
async def get_me(user: UserInfo = Depends(require_auth)):
    """
    Get current authenticated user information.
    """
    return user


@router.get("/status")
async def auth_status():
    """
    Check authentication configuration status.
    """
    settings = get_azure_settings()
    return {
        "enabled": settings.AZURE_AUTH_ENABLED,
        "configured": bool(settings.AZURE_CLIENT_ID and settings.AZURE_TENANT_ID),
        "tenant_id": settings.AZURE_TENANT_ID[:8] + "..." if settings.AZURE_TENANT_ID else None,
    }
