"""
Data Quality Routes - Domain-Separated
Generated by RTX 5090 (Qwen2.5-Coder-32B-Instruct-AWQ)
"""
from fastapi import APIRouter, HTTPException, Body
from pydantic import BaseModel
from typing import List, Optional, Dict, Any

from app.services.data_quality_rules import DataQualityRulesService
from app.config import settings

router = APIRouter(
    prefix="/data-quality",
    tags=["Data Quality"]
)


class RuleCreate(BaseModel):
    """Request model for creating a data quality rule."""
    name: str
    table: str
    column: str
    rule_type: str
    definition: str  # SQL query or rule definition
    severity: str = "medium"


class RuleResponse(BaseModel):
    """Response model for a data quality rule."""
    id: Optional[int] = None
    name: str
    table: str
    column: str
    rule_type: str
    definition: str
    severity: str
    is_active: bool = True


class ExecutionResult(BaseModel):
    """Response model for rule execution result."""
    rule_id: int
    passed: bool
    failures: List[str]


def get_service() -> DataQualityRulesService:
    """Get the data quality rules service instance."""
    return DataQualityRulesService(settings.DATABASE_URL)


@router.get("/rules", response_model=List[RuleResponse])
async def list_rules():
    """
    List all data quality rules.

    Returns a list of all active data quality rules.
    """
    try:
        service = get_service()
        rules = await service.get_all_rules()
        return [RuleResponse(**r) if isinstance(r, dict) else r for r in rules]
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list rules: {str(e)}")


@router.post("/rules", response_model=dict, status_code=201)
async def create_rule(rule: RuleCreate):
    """
    Create a new data quality rule.

    Creates a rule that can be executed against the database.
    """
    try:
        service = get_service()
        await service.create_rule(
            name=rule.name,
            table=rule.table,
            column=rule.column,
            rule_type=rule.rule_type,
            definition=rule.definition,
            severity=rule.severity
        )
        return {"message": "Rule created successfully", "name": rule.name}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create rule: {str(e)}")


@router.get("/rules/{rule_id}", response_model=RuleResponse)
async def get_rule(rule_id: int):
    """
    Get a specific data quality rule.

    Returns details of a single rule by ID.
    """
    try:
        service = get_service()
        rules = await service.get_all_rules()
        for rule in rules:
            if isinstance(rule, dict) and rule.get('id') == rule_id:
                return RuleResponse(**rule)
        raise HTTPException(status_code=404, detail="Rule not found")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to get rule: {str(e)}")


@router.post("/rules/{rule_id}/execute")
async def execute_rule(rule_id: int):
    """
    Execute a data quality rule.

    Runs the rule against the database and returns pass/fail status.
    """
    try:
        service = get_service()
        result = await service.execute_rule(rule_id)
        failures = await service.get_failures(rule_id)
        return {
            "rule_id": rule_id,
            "executed": True,
            "failures_count": len(failures),
            "failures": failures[:10]  # Return first 10 failures
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to execute rule: {str(e)}")


@router.post("/suggest")
async def suggest_rules(profile_data: List[Dict[str, Any]] = Body(...)):
    """
    Suggest data quality rules based on profiling results.

    Analyzes profiling data and suggests appropriate rules.
    """
    try:
        service = get_service()
        suggestions = await service.suggest_rules(profile_data)
        return {"suggestions": suggestions}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to suggest rules: {str(e)}")


@router.get("/results")
async def get_results():
    """
    Get all rule execution results.

    Returns historical execution results for all rules.
    """
    try:
        service = get_service()
        # Get results for all rules by collecting failures
        rules = await service.get_all_rules()
        results = []
        for rule in rules:
            rule_id = rule.get('id') if isinstance(rule, dict) else getattr(rule, 'id', None)
            if rule_id:
                failures = await service.get_failures(rule_id)
                results.append({
                    "rule_id": rule_id,
                    "failures_count": len(failures),
                    "has_failures": len(failures) > 0
                })
        return {"results": results}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to get results: {str(e)}")
