"""
Data Profiling Routes - Domain-Separated
Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
Enhanced for production use.
V79: Added batch profiling for multi-table selection.
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Dict, Any

from app.services.data_profiling_service import get_profiling_service
from app.config import settings


# Pydantic models for batch operations (V79)
class BatchProfileRequest(BaseModel):
    """Request model for batch profiling multiple tables."""
    tables: List[str]


class TableProfileResult(BaseModel):
    """Result model for a single table profile."""
    table_name: str
    profile_data: Dict[str, Any]
    success: bool = True
    error: str = None

router = APIRouter(
    prefix="/data-profiling",
    tags=["Data Profiling"]
)


@router.get("/tables", response_model=List[str])
async def list_tables():
    """
    List all available tables from the database.

    Returns a list of table names that are in the whitelist
    and available for profiling.
    """
    try:
        service = await get_profiling_service()
        tables = await service.get_tables()
        return tables
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list tables: {str(e)}")


@router.get("/profile/{table}")
async def profile_table(table: str):
    """
    Profile a specific table with REAL database queries.

    Returns detailed statistics for each column including:
    - Row count
    - Null counts and percentages
    - Unique value counts
    - Min/max values for numeric columns
    - Sample values
    """
    if table not in settings.TABLE_WHITELIST:
        raise HTTPException(
            status_code=400,
            detail=f"Table '{table}' is not in the whitelist. Allowed: {sorted(settings.TABLE_WHITELIST)}"
        )

    try:
        service = await get_profiling_service()
        profile = await service.profile_table(table)
        return profile.to_dict()
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to profile table: {str(e)}")


@router.post("/profile/{table}/run")
async def run_profile(table: str):
    """
    Run profiling on a table and STORE results.

    V85: Fixed to store profiling results for DQ rule suggestions.
    This endpoint matches the Expert AI pattern for compatibility.
    Results are stored in the database for later use by rule suggestions.
    """
    if table not in settings.TABLE_WHITELIST:
        raise HTTPException(
            status_code=400,
            detail=f"Table '{table}' is not in the whitelist. Allowed: {sorted(settings.TABLE_WHITELIST)}"
        )

    try:
        service = await get_profiling_service()
        profile = await service.profile_and_store(table)
        return {
            "table": table,
            "columns_profiled": len(profile.columns),
            "stored": True,
            "row_count": profile.row_count
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to profile table: {str(e)}")


@router.post("/profile/{table}/store")
async def profile_and_store(table: str):
    """
    Profile a table and store results for rule suggestion.

    Profiles the table and stores results in the database for later
    use by the rule suggestion endpoint.
    """
    if table not in settings.TABLE_WHITELIST:
        raise HTTPException(
            status_code=400,
            detail=f"Table '{table}' is not in the whitelist. Allowed: {sorted(settings.TABLE_WHITELIST)}"
        )

    try:
        service = await get_profiling_service()
        profile = await service.profile_and_store(table)
        return {
            "message": f"Profile stored for table {table}",
            "table_name": table,
            "columns_profiled": len(profile.columns),
            "row_count": profile.row_count
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to profile and store: {str(e)}")


@router.post("/profile/all/store")
async def profile_all_and_store():
    """
    Profile all whitelisted tables and store results.

    This endpoint profiles all available tables and stores the results
    for later use by the rule suggestion endpoint.
    """
    try:
        service = await get_profiling_service()
        profiles = await service.profile_all_tables()
        return {
            "message": f"Profiled and stored {len(profiles)} tables",
            "tables": [p.table_name for p in profiles],
            "total_columns": sum(len(p.columns) for p in profiles)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to profile all tables: {str(e)}")


@router.get("/results")
async def get_stored_results(table_name: str = None, limit: int = 50):
    """
    Get stored profiling results.

    Returns previously stored profiling results, optionally filtered by table.
    """
    try:
        service = await get_profiling_service()
        results = await service.get_stored_results(table_name=table_name, limit=limit)
        return {
            "results": results,
            "count": len(results),
            "table_filter": table_name
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to get stored results: {str(e)}")


# V79: Batch profiling endpoint for multi-table selection
@router.post("/profile/batch")
async def batch_profile_tables(request: BatchProfileRequest):
    """
    Profile multiple tables in batch.

    V79 Enhancement: Supports multi-table selection UI.
    Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct).

    Args:
        request: BatchProfileRequest with list of table names

    Returns:
        List of profile results for each table, including any errors
    """
    results = []
    service = await get_profiling_service()

    for table in request.tables:
        if table not in settings.TABLE_WHITELIST:
            results.append(TableProfileResult(
                table_name=table,
                profile_data={},
                success=False,
                error=f"Table '{table}' not in whitelist"
            ))
            continue

        try:
            profile = await service.profile_table(table)
            results.append(TableProfileResult(
                table_name=table,
                profile_data=profile.to_dict()
            ))
        except Exception as e:
            results.append(TableProfileResult(
                table_name=table,
                profile_data={},
                success=False,
                error=str(e)
            ))

    return {
        "profiles": [r.dict() for r in results],
        "total": len(results),
        "successful": sum(1 for r in results if r.success),
        "failed": sum(1 for r in results if not r.success)
    }
