"""
Data Profiling Routes - Domain-Separated
Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
Enhanced for production use.
"""
from fastapi import APIRouter, HTTPException
from typing import List

from app.services.data_profiling_service import get_profiling_service
from app.config import settings

router = APIRouter(
    prefix="/data-profiling",
    tags=["Data Profiling"]
)


@router.get("/tables", response_model=List[str])
async def list_tables():
    """
    List all available tables from the database.

    Returns a list of table names that are in the whitelist
    and available for profiling.
    """
    try:
        service = await get_profiling_service()
        tables = await service.get_tables()
        return tables
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list tables: {str(e)}")


@router.get("/profile/{table}")
async def profile_table(table: str):
    """
    Profile a specific table with REAL database queries.

    Returns detailed statistics for each column including:
    - Row count
    - Null counts and percentages
    - Unique value counts
    - Min/max values for numeric columns
    - Sample values
    """
    if table not in settings.TABLE_WHITELIST:
        raise HTTPException(
            status_code=400,
            detail=f"Table '{table}' is not in the whitelist. Allowed: {sorted(settings.TABLE_WHITELIST)}"
        )

    try:
        service = await get_profiling_service()
        profile = await service.profile_table(table)
        return profile.to_dict()
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to profile table: {str(e)}")


@router.post("/profile/{table}/run")
async def run_profile(table: str):
    """
    Run profiling on a table and return results.

    This endpoint matches the Expert AI pattern for compatibility.
    """
    return await profile_table(table)
