"""
Data Profiling Routes - Domain-Separated
Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
Enhanced for production use.
"""
from fastapi import APIRouter, HTTPException
from typing import List

from app.services.data_profiling_service import get_profiling_service
from app.config import settings

router = APIRouter(
    prefix="/data-profiling",
    tags=["Data Profiling"]
)


@router.get("/tables", response_model=List[str])
async def list_tables():
    """
    List all available tables from the database.

    Returns a list of table names that are in the whitelist
    and available for profiling.
    """
    try:
        service = await get_profiling_service()
        tables = await service.get_tables()
        return tables
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list tables: {str(e)}")


@router.get("/profile/{table}")
async def profile_table(table: str):
    """
    Profile a specific table with REAL database queries.

    Returns detailed statistics for each column including:
    - Row count
    - Null counts and percentages
    - Unique value counts
    - Min/max values for numeric columns
    - Sample values
    """
    if table not in settings.TABLE_WHITELIST:
        raise HTTPException(
            status_code=400,
            detail=f"Table '{table}' is not in the whitelist. Allowed: {sorted(settings.TABLE_WHITELIST)}"
        )

    try:
        service = await get_profiling_service()
        profile = await service.profile_table(table)
        return profile.to_dict()
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to profile table: {str(e)}")


@router.post("/profile/{table}/run")
async def run_profile(table: str):
    """
    Run profiling on a table and return results.

    This endpoint matches the Expert AI pattern for compatibility.
    """
    return await profile_table(table)


@router.post("/profile/{table}/store")
async def profile_and_store(table: str):
    """
    Profile a table and store results for rule suggestion.

    Profiles the table and stores results in the database for later
    use by the rule suggestion endpoint.
    """
    if table not in settings.TABLE_WHITELIST:
        raise HTTPException(
            status_code=400,
            detail=f"Table '{table}' is not in the whitelist. Allowed: {sorted(settings.TABLE_WHITELIST)}"
        )

    try:
        service = await get_profiling_service()
        profile = await service.profile_and_store(table)
        return {
            "message": f"Profile stored for table {table}",
            "table_name": table,
            "columns_profiled": len(profile.columns),
            "row_count": profile.row_count
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to profile and store: {str(e)}")


@router.post("/profile/all/store")
async def profile_all_and_store():
    """
    Profile all whitelisted tables and store results.

    This endpoint profiles all available tables and stores the results
    for later use by the rule suggestion endpoint.
    """
    try:
        service = await get_profiling_service()
        profiles = await service.profile_all_tables()
        return {
            "message": f"Profiled and stored {len(profiles)} tables",
            "tables": [p.table_name for p in profiles],
            "total_columns": sum(len(p.columns) for p in profiles)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to profile all tables: {str(e)}")


@router.get("/results")
async def get_stored_results(table_name: str = None, limit: int = 50):
    """
    Get stored profiling results.

    Returns previously stored profiling results, optionally filtered by table.
    """
    try:
        service = await get_profiling_service()
        results = await service.get_stored_results(table_name=table_name, limit=limit)
        return {
            "results": results,
            "count": len(results),
            "table_filter": table_name
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to get stored results: {str(e)}")
