"""
Data Lineage Routes
Generated by: RTX 3050 (skeleton), Expert AI (enhancement)
"""
from fastapi import APIRouter, HTTPException
from typing import Optional
from pydantic import BaseModel

from app.services.lineage_service import get_lineage_service

router = APIRouter(
    prefix="/lineage",
    tags=["Data Lineage"]
)


class LineageTrackRequest(BaseModel):
    source_table: str
    source_column: Optional[str] = None
    target_table: str
    target_column: Optional[str] = None
    transformation_type: str = "direct"
    transformation_details: Optional[str] = None


@router.post("/track")
async def track_lineage(request: LineageTrackRequest):
    """Track data lineage between tables/columns."""
    try:
        service = await get_lineage_service()
        lineage_id = await service.track_lineage(
            source_table=request.source_table,
            source_column=request.source_column,
            target_table=request.target_table,
            target_column=request.target_column,
            transformation_type=request.transformation_type,
            transformation_details=request.transformation_details
        )
        return {"status": "success", "lineage_id": lineage_id}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/table/{table_name}")
async def get_table_lineage(table_name: str):
    """Get all lineage records for a table."""
    try:
        service = await get_lineage_service()
        lineage = await service.get_table_lineage(table_name)
        return {"table": table_name, "lineage": lineage}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/upstream/{table_name}")
async def get_upstream_tables(table_name: str):
    """Get upstream (source) tables."""
    try:
        service = await get_lineage_service()
        upstream = await service.get_upstream(table_name)
        return {"table": table_name, "upstream": upstream}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/downstream/{table_name}")
async def get_downstream_tables(table_name: str):
    """Get downstream (target) tables."""
    try:
        service = await get_lineage_service()
        downstream = await service.get_downstream(table_name)
        return {"table": table_name, "downstream": downstream}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/impact/{table_name}")
async def get_impact_analysis(table_name: str):
    """Analyze impact of changes to a table."""
    try:
        service = await get_lineage_service()
        impact = await service.get_impact_analysis(table_name)
        return impact
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
