"""
Report Generation Routes
Generated by: RTX 3050 (skeleton), Expert AI (enhancement)
"""
from fastapi import APIRouter, HTTPException, Query
from typing import Optional
from pydantic import BaseModel

from app.services.report_service import get_report_service

router = APIRouter(
    prefix="/reports",
    tags=["Reports"]
)


class ReportGenerateRequest(BaseModel):
    report_type: str = "dq_summary"
    output_format: str = "json"
    table_name: Optional[str] = None
    data: Optional[dict] = None


@router.get("/templates")
async def list_templates():
    """List available report templates."""
    service = await get_report_service()
    return {"templates": service.get_report_templates()}


@router.post("/generate")
async def generate_report(request: ReportGenerateRequest):
    """Generate a data quality report."""
    try:
        service = await get_report_service()
        
        data = request.data or {
            "table": request.table_name,
            "generated_by": "dqm-local-ai"
        }
        
        result = await service.generate_report(
            report_type=request.report_type,
            data=data,
            output_format=request.output_format
        )
        return result
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/summary")
async def get_dq_summary(table_name: Optional[str] = Query(None)):
    """Get data quality summary report."""
    try:
        service = await get_report_service()
        result = await service.generate_dq_summary(table_name)
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
