"""
Configuration Management using Pydantic Settings
Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
Enhanced with additional settings.
"""
from pydantic_settings import BaseSettings, SettingsConfigDict
from typing import FrozenSet, Set, List
from functools import lru_cache


class Settings(BaseSettings):
    """Centralized configuration for DQM LOCAL AI application."""

    # Database settings
    DATABASE_URL: str = "postgresql://dqm_user:dqm_password@localhost:5432/northwind"
    DATABASE_MIN_POOL_SIZE: int = 2
    DATABASE_MAX_POOL_SIZE: int = 10

    # Table whitelist - security constraint
    TABLE_WHITELIST: FrozenSet[str] = frozenset({
        "customers", "orders", "products", "employees", "order_details",
        "categories", "shippers", "suppliers", "territories", "region"
    })

    # Logging
    LOG_LEVEL: str = "INFO"
    LOG_FORMAT: str = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    # API settings
    API_PREFIX: str = "/api"
    API_TITLE: str = "DQM LOCAL AI"
    API_VERSION: str = "1.0.0"

    # CORS settings
    CORS_ORIGINS: List[str] = [
        "http://localhost:3000",
        "http://localhost:3001",
        "http://localhost:5173",
        "http://localhost:8000"
    ]

    # LOCAL AI settings (RTX 5090)
    LOCAL_AI_RTX5090_URL: str = "http://localhost:8004/v1"
    LOCAL_AI_RTX5090_MODEL: str = "Qwen/Qwen2.5-Coder-32B-Instruct-AWQ"
    LOCAL_AI_TIMEOUT: int = 180

    # RTX 3050 settings (for lighter tasks)
    LOCAL_AI_RTX3050_URL: str = "http://localhost:8015/v1"
    LOCAL_AI_RTX3050_MODEL: str = "qwen2.5-coder-7b-instruct"

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        validate_assignment=True,
        extra="ignore"
    )


@lru_cache
def get_settings() -> Settings:
    """Get cached configuration singleton."""
    return Settings()


# Convenience alias for backward compatibility
settings = get_settings()

# Backward compatibility exports
DATABASE_URL = settings.DATABASE_URL
LOCAL_AI_RTX5090_URL = settings.LOCAL_AI_RTX5090_URL
LOCAL_AI_RTX3050_URL = settings.LOCAL_AI_RTX3050_URL
CORS_ORIGINS = settings.CORS_ORIGINS
