"""
SQLAlchemy Database Layer - Async Support
Generated by RTX 5090 (Qwen2.5-Coder-32B-Instruct-AWQ)
Enhanced for proper integration with existing services.
"""
from contextlib import asynccontextmanager
from typing import AsyncGenerator
import logging

from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker
from sqlalchemy.pool import NullPool
from sqlalchemy import text

from app.config import settings

logger = logging.getLogger(__name__)

# Create async engine with NullPool for async compatibility
# Note: Using asyncpg driver (postgresql+asyncpg://)
DATABASE_URL = settings.DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://")

engine = create_async_engine(
    DATABASE_URL,
    echo=False,
    poolclass=NullPool,  # Recommended for async to avoid connection issues
)

async_session_maker = async_sessionmaker(
    engine,
    class_=AsyncSession,
    expire_on_commit=False
)


@asynccontextmanager
async def lifespan(app):
    """
    Modern lifespan context manager for FastAPI.

    Startup: Verify database connection
    Shutdown: Dispose of engine
    """
    logger.info("Starting DQM LOCAL AI API with SQLAlchemy...")

    # Verify database connection on startup
    async with engine.begin() as conn:
        await conn.execute(text("SELECT 1"))
    logger.info("Database connection verified")

    yield

    # Cleanup on shutdown
    logger.info("Shutting down DQM LOCAL AI API...")
    await engine.dispose()
    logger.info("Database engine disposed")


async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """
    FastAPI dependency for database sessions with transaction management.

    Usage:
        @router.get("/items")
        async def get_items(db: AsyncSession = Depends(get_db)):
            result = await db.execute(select(Item))
            return result.scalars().all()

    Features:
    - Automatic session cleanup
    - Transaction commit on success
    - Transaction rollback on exception
    """
    async with async_session_maker() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


# Export for backward compatibility with existing code
# Existing code can still use asyncpg directly via data_profiling_service
# New code should use SQLAlchemy via get_db dependency
