"""
Exception Handling Module for DQM Application
Generated by RTX 5090 (Qwen2.5-Coder-32B-AWQ)
"""
from fastapi import Request, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typing import Optional
import time


class ProblemDetail(BaseModel):
    """RFC 7807 compliant problem details."""
    type: str = "about:blank"
    title: str
    status: int
    detail: Optional[str] = None
    instance: Optional[str] = None


class DQMException(Exception):
    """Base class for all custom exceptions."""
    status_code: int = status.HTTP_500_INTERNAL_SERVER_ERROR

    def __init__(self, detail: str, instance: Optional[str] = None):
        self.detail = detail
        self.instance = instance
        super().__init__(detail)


class ValidationError(DQMException):
    """Exception raised for errors in the input validation."""
    status_code = status.HTTP_400_BAD_REQUEST


class DatabaseError(DQMException):
    """Exception raised for database related errors."""
    status_code = status.HTTP_503_SERVICE_UNAVAILABLE


class AIServiceError(DQMException):
    """Exception raised for AI service related errors."""
    status_code = status.HTTP_503_SERVICE_UNAVAILABLE


class ResourceNotFoundError(DQMException):
    """Exception raised when a resource is not found."""
    status_code = status.HTTP_404_NOT_FOUND


class CircuitBreakerOpen(Exception):
    """Exception raised when the circuit breaker is open."""
    pass


class CircuitBreaker:
    """
    Implements a simple circuit breaker pattern.

    States:
        CLOSED: Normal operation, requests flow through
        OPEN: Too many failures, requests are blocked
        HALF_OPEN: Testing if service recovered
    """
    STATE_CLOSED = 'CLOSED'
    STATE_OPEN = 'OPEN'
    STATE_HALF_OPEN = 'HALF_OPEN'

    def __init__(self, failure_threshold: int = 5, recovery_timeout: int = 30):
        self.state = self.STATE_CLOSED
        self.failure_count = 0
        self.failure_threshold = failure_threshold
        self.recovery_timeout = recovery_timeout
        self.last_failure_time = 0.0

    def record_failure(self) -> None:
        """Records a failure and transitions the state if necessary."""
        self.failure_count += 1
        self.last_failure_time = time.time()
        if self.failure_count >= self.failure_threshold:
            self.state = self.STATE_OPEN

    def record_success(self) -> None:
        """Records a success and resets the failure count."""
        if self.state == self.STATE_HALF_OPEN:
            self.state = self.STATE_CLOSED
        self.failure_count = 0

    def allow_request(self) -> bool:
        """Determines if a request is allowed based on the current state."""
        if self.state == self.STATE_CLOSED:
            return True
        elif self.state == self.STATE_HALF_OPEN:
            return True
        elif self.state == self.STATE_OPEN:
            if time.time() - self.last_failure_time > self.recovery_timeout:
                self.state = self.STATE_HALF_OPEN
                return True
        return False

    def __call__(self) -> None:
        """Check if request should be allowed, raise if not."""
        if not self.allow_request():
            raise CircuitBreakerOpen("Circuit breaker is open")


async def dqm_exception_handler(request: Request, exc: DQMException) -> JSONResponse:
    """Handles DQMException and returns RFC 7807 problem details."""
    problem_detail = ProblemDetail(
        type="about:blank",
        title=exc.__class__.__name__,
        status=exc.status_code,
        detail=exc.detail,
        instance=str(request.url)
    )
    return JSONResponse(
        content=problem_detail.model_dump(),
        status_code=exc.status_code
    )


async def circuit_breaker_handler(request: Request, exc: CircuitBreakerOpen) -> JSONResponse:
    """Handles CircuitBreakerOpen exception."""
    problem_detail = ProblemDetail(
        type="about:blank",
        title="Service Unavailable",
        status=status.HTTP_503_SERVICE_UNAVAILABLE,
        detail="Service temporarily unavailable due to circuit breaker",
        instance=str(request.url)
    )
    return JSONResponse(
        content=problem_detail.model_dump(),
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE
    )


def register_exception_handlers(app) -> None:
    """Register all exception handlers with the FastAPI app."""
    app.add_exception_handler(DQMException, dqm_exception_handler)
    app.add_exception_handler(ValidationError, dqm_exception_handler)
    app.add_exception_handler(DatabaseError, dqm_exception_handler)
    app.add_exception_handler(AIServiceError, dqm_exception_handler)
    app.add_exception_handler(ResourceNotFoundError, dqm_exception_handler)
    app.add_exception_handler(CircuitBreakerOpen, circuit_breaker_handler)
