/**
 * App.jsx - Local AI DQM Application
 * V84: Refactored to match Expert AI component architecture for 100% feature parity
 * Generated by Claude Code with RTX 5090/3050 architecture
 */
import React, { useState, useEffect } from 'react';
import DataProfiling from './components/DataProfiling';
import DataQualityRules from './components/DataQualityRules';
import RootCauseAnalysis from './components/RootCauseAnalysis';
import DatabaseConnectionManager from './components/DatabaseConnectionManager';
import './App.css';

const API_BASE = 'http://localhost:8001';

function App() {
  const [activeTab, setActiveTab] = useState('profiling');
  const [health, setHealth] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch(`${API_BASE}/health`)
      .then(res => res.json())
      .then(data => setHealth(data))
      .catch(err => setError('API not available'));
  }, []);

  const tabs = [
    { id: 'profiling', label: 'Data Profiling', icon: '📊' },
    { id: 'rules', label: 'Quality Rules', icon: '✓' },
    { id: 'analysis', label: 'Root Cause Analysis', icon: '🔍' },
    { id: 'settings', label: 'Settings', icon: '⚙️' },
  ];

  return (
    <div className="app">
      <header className="app-header">
        <h1>Data Quality Management</h1>
        <span className="version">LOCAL AI v1.0</span>
        {health && <span className="status healthy">● API Connected</span>}
        {error && <span className="status error">● {error}</span>}
      </header>

      <nav className="tabs">
        {tabs.map(tab => (
          <button
            key={tab.id}
            className={`tab ${activeTab === tab.id ? 'active' : ''}`}
            onClick={() => setActiveTab(tab.id)}
          >
            <span className="icon">{tab.icon}</span>
            {tab.label}
          </button>
        ))}
      </nav>

      <main className="content">
        {activeTab === 'profiling' && <DataProfiling apiBase={API_BASE} />}
        {activeTab === 'rules' && <DataQualityRules apiBase={API_BASE} />}
        {activeTab === 'analysis' && <RootCauseAnalysis apiBase={API_BASE} />}
        {activeTab === 'settings' && (
          <div className="settings-section">
            <h2>Settings</h2>
            <DatabaseConnectionManager apiBase={API_BASE} />
          </div>
        )}
      </main>

      <footer className="app-footer">
        <p>Generated by LOCAL AI | Using RTX 5090 + RTX 3050 for analysis</p>
      </footer>
    </div>
  );
}

export default App;
