"""
API Authentication Module for FastAPI
Generated by RTX 5090 (Qwen2.5-Coder-32B-AWQ)
"""
from fastapi import Header, HTTPException, Depends
from typing import Optional, Set
import os
import hmac


class AuthenticationError(Exception):
    """Custom exception class for authentication errors."""
    pass


def load_valid_api_keys() -> Set[str]:
    """
    Load valid API keys from the environment variable.

    Returns:
        A set of valid API keys.
    """
    api_keys_env = os.getenv("VALID_API_KEYS", "")
    if not api_keys_env:
        return set()
    return set(key.strip() for key in api_keys_env.split(",") if key.strip())


def secure_compare(val1: str, val2: str) -> bool:
    """
    Securely compare two strings to prevent timing attacks.

    Args:
        val1: The first string to compare.
        val2: The second string to compare.

    Returns:
        True if the strings are equal, False otherwise.
    """
    return hmac.compare_digest(val1.encode(), val2.encode())


def verify_api_key(x_api_key: Optional[str] = Header(None)) -> bool:
    """
    Verify the API key provided in the X-API-Key header.

    Args:
        x_api_key: The API key from the X-API-Key header.

    Raises:
        HTTPException: If the API key is missing or invalid.

    Returns:
        True if the API key is valid.
    """
    valid_api_keys = load_valid_api_keys()

    # If no API keys configured, allow all requests (development mode)
    if not valid_api_keys:
        return True

    if not x_api_key:
        raise HTTPException(status_code=401, detail="API key is missing")

    if not any(secure_compare(x_api_key, key) for key in valid_api_keys):
        raise HTTPException(status_code=401, detail="Invalid API key")

    return True


async def get_api_key_dependency(
    api_key_verified: bool = Depends(verify_api_key)
) -> bool:
    """
    Dependency function to ensure API key verification before accessing protected routes.

    Args:
        api_key_verified: Boolean indicating if the API key was verified.

    Returns:
        True if the API key is verified.
    """
    return api_key_verified
