"""
CORS Configuration for FastAPI
Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from typing import List
import os


def validate_origin(origin: str) -> bool:
    """Validate if an origin is in the allowed list."""
    allowed_origins = get_allowed_origins()
    return origin in allowed_origins


def get_allowed_origins() -> List[str]:
    """Get allowed origins based on environment."""
    if os.getenv("ENVIRONMENT") == "production":
        # In production, use strict origin list
        return [os.getenv("ALLOWED_ORIGIN", "http://localhost")]
    else:
        # In development, allow multiple origins
        return os.getenv(
            "ALLOWED_ORIGINS",
            "http://localhost,http://localhost:3000,http://localhost:5173"
        ).split(",")


def configure_cors(app: FastAPI) -> None:
    """Configure CORS middleware for the FastAPI application."""
    allowed_origins = get_allowed_origins()

    app.add_middleware(
        CORSMiddleware,
        allow_origins=allowed_origins,
        allow_credentials=True,
        allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        allow_headers=["*"],
    )
