"""
Request Logging Middleware for FastAPI
Generated by RTX 3050 (Qwen2.5-Coder-7B-Instruct)
"""
import time
import logging
import json
from typing import Callable, Any
from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware
import os

# Configure logger
logging.basicConfig(
    level=logging.getLevelName(os.getenv("LOG_LEVEL", "INFO")),
    format='%(message)s'
)
logger = logging.getLogger(__name__)


class RequestLoggingMiddleware(BaseHTTPMiddleware):
    """Middleware for logging all incoming requests with structured JSON format."""

    SENSITIVE_HEADERS = {"authorization", "x-api-key", "cookie", "set-cookie"}

    def __init__(self, app: Callable[..., Any]):
        super().__init__(app)
        self.log_level = os.getenv("LOG_LEVEL", "INFO")

    async def dispatch(self, request: Request, call_next) -> Response:
        start_time = time.time()

        # Process request
        response = await call_next(request)

        # Calculate duration
        duration_ms = (time.time() - start_time) * 1000

        # Build log data
        log_data = {
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "method": request.method,
            "path": request.url.path,
            "query": str(request.query_params) if request.query_params else None,
            "ip": self._get_client_ip(request),
            "status": response.status_code,
            "duration_ms": round(duration_ms, 2),
            "user_agent": request.headers.get("user-agent", "unknown")
        }

        # Sanitize and add headers (redact sensitive ones)
        sanitized_headers = self._sanitize_headers(dict(request.headers))
        if sanitized_headers:
            log_data["headers"] = sanitized_headers

        # Log as JSON
        logger.info(json.dumps(log_data))

        return response

    def _get_client_ip(self, request: Request) -> str:
        """Get client IP, handling proxies."""
        x_forwarded_for = request.headers.get("x-forwarded-for")
        if x_forwarded_for:
            return x_forwarded_for.split(",")[0].strip()
        return request.client.host if request.client else "unknown"

    def _sanitize_headers(self, headers: dict) -> dict:
        """Redact sensitive headers."""
        sanitized = {}
        for key, value in headers.items():
            if key.lower() in self.SENSITIVE_HEADERS:
                sanitized[key] = "[REDACTED]"
            else:
                sanitized[key] = value
        return sanitized
